site_name: 'Sushi for Compose UI'
site_description: "Sushi UI is a comprehensive design system for Jetpack Compose that provides a rich set of customizable components for building beautiful, consistent, and accessible user interfaces."
site_url: https://zomato.com/compose-sushi
docs_dir: 'docs'
site_dir: build/site

repo_name: 'Compose-Sushi'
repo_url: https://github.com/Zomato/compose-sushi

theme:
  name: material
  favicon: assets/logo.png
  logo: assets/logo.png
  font:
    text: Fira Sans
    code: Jetbrains Mono
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'white'
      accent: 'gray'
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'black'
      accent: 'gray'
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Overview:
      - Introduction: introduction.md
  - Components:
      - 'SushiText': sushitext.md
      - 'SushiIcon': sushiicon.md
      - 'SushiButton': sushibutton.md
      - 'SushiImage': sushiimage.md
      - 'SushiCheckBox': sushicheckbox.md
      - 'SushiRadioButton': sushiradiobutton.md
      - 'SushiSwitch': sushiswitch.md
      - 'SushiTag': sushitag.md
      - 'SushiTextField': sushitextfield.md
      - 'SushiAnimation': sushianimation.md
      - 'SushiLoader': sushiloader.md
      - 'SushiCard': sushicard.md
      - 'SushiIndicator': sushiindicator.md
      - 'SushiDivider': sushidivider.md
      - 'SushiShimmer': sushishimmer.md
      - 'SushiSnackbar': sushisnackbar.md
      - 'SushiBottomSheet': sushibottomsheet.md
      - 'SushiDialog': sushidialog.md
      - 'SushiDropDown': sushidropdown.md
      - 'SushiMedia': sushimedia.md
      - 'SushiOTPInput': sushiotpinput.md
      - 'SushiHorizontalPager': sushihorizontalpager.md
      - 'SushiVerticalPager': sushiverticalpager.md
      - 'SushiRatingBar': sushiratingbar.md
      - 'SushiTooltip': sushitooltip.md
      - 'SushiViewFlipper': sushiviewflipper.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  <a href="https://github.com/Zomato/compose-sushi"><img  src="sushi.svg"></a>