#!/bin/bash

set -e  # Exit on any error

echo "🔧 Setting up Android SDK..."

# Function to check if command exists
command_exists() {
    command -v "$1" >/dev/null 2>&1
}

# Install Android SDK using brew (macOS)
if ! command_exists sdkmanager; then
    echo "📦 Installing Android SDK command line tools..."
    if command_exists brew; then
        brew install --cask android-commandlinetools
    else
        echo "❌ Error: Homebrew not found. Please install Homebrew first."
        exit 1
    fi
else
    echo "✅ Android SDK command line tools already installed"
fi

# Set up Android SDK environment variables
export ANDROID_HOME=$HOME/Library/Android/sdk
export ANDROID_SDK_ROOT=$ANDROID_HOME
export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools

echo "📁 Android SDK Home: $ANDROID_HOME"

# Create SDK directory if it doesn't exist
mkdir -p $ANDROID_HOME

# Accept licenses
echo "📄 Accepting Android SDK licenses..."
yes | sdkmanager --licenses 2>/dev/null || echo "✅ License acceptance completed"

# Install required SDK components
echo "📦 Installing Android SDK components..."
SDK_COMPONENTS=(
    "platform-tools"
    "platforms;android-34"
    "platforms;android-33"
    "build-tools;34.0.0"
    "build-tools;33.0.2"
    "cmdline-tools;latest"
)

for component in "${SDK_COMPONENTS[@]}"; do
    echo "Installing $component..."
    sdkmanager "$component" || echo "⚠️  Failed to install $component, continuing..."
done

# Create local.properties file
echo "📝 Creating local.properties file..."
cat > local.properties << EOF
## This file is automatically generated by setup-android-sdk.sh
# Do not modify this file manually in the repository.
# This file should *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the Android SDK. This is used by Gradle.
sdk.dir=$ANDROID_HOME
EOF

# Verify local.properties was created
if [ -f "local.properties" ]; then
    echo "✅ local.properties created successfully"
    echo "Contents:"
    cat local.properties
else
    echo "❌ Failed to create local.properties"
    exit 1
fi

# Export environment variables for the current shell session
echo ""
echo "🌍 Setting up environment variables..."
echo "export ANDROID_HOME=$ANDROID_HOME"
echo "export ANDROID_SDK_ROOT=$ANDROID_HOME"
echo "export PATH=\$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools"

# Verify SDK installation
echo ""
echo "🔍 Verifying Android SDK installation..."
if command_exists adb; then
    echo "✅ ADB: $(adb --version | head -1)"
else
    echo "⚠️  ADB not found in PATH"
fi

if command_exists sdkmanager; then
    echo "✅ SDK Manager: Available"
    echo "📦 Installed packages:"
    sdkmanager --list_installed | grep -E "(platforms|build-tools|platform-tools)" | head -10
else
    echo "❌ SDK Manager not found"
fi

echo ""
echo "✅ Android SDK setup completed successfully!"
echo "🎯 You can now run Gradle builds that require Android SDK"