package com.zomato.sushi.compose.atoms.textfield

import androidx.compose.foundation.text.selection.TextSelectionColors
import androidx.compose.material3.TextFieldColors
import androidx.compose.runtime.Composable
import androidx.compose.runtime.Immutable
import com.zomato.sushi.compose.atoms.color.ColorSpec

@Immutable
data class SushiTextFieldColors(
    val focusedTextColor: ColorSpec,
    val unfocusedTextColor: ColorSpec,
    val disabledTextColor: ColorSpec,
    val errorTextColor: ColorSpec,
    val focusedContainerColor: ColorSpec,
    val unfocusedContainerColor: ColorSpec,
    val disabledContainerColor: ColorSpec,
    val errorContainerColor: ColorSpec,
    val cursorColor: ColorSpec,
    val errorCursorColor: ColorSpec,
    val textSelectionColors: TextSelectionColors,
    val focusedIndicatorColor: ColorSpec,
    val unfocusedIndicatorColor: ColorSpec,
    val disabledIndicatorColor: ColorSpec,
    val errorIndicatorColor: ColorSpec,
    val focusedLeadingIconColor: ColorSpec,
    val unfocusedLeadingIconColor: ColorSpec,
    val disabledLeadingIconColor: ColorSpec,
    val errorLeadingIconColor: ColorSpec,
    val focusedTrailingIconColor: ColorSpec,
    val unfocusedTrailingIconColor: ColorSpec,
    val disabledTrailingIconColor: ColorSpec,
    val errorTrailingIconColor: ColorSpec,
    val focusedLabelColor: ColorSpec,
    val unfocusedLabelColor: ColorSpec,
    val disabledLabelColor: ColorSpec,
    val errorLabelColor: ColorSpec,
    val focusedPlaceholderColor: ColorSpec,
    val unfocusedPlaceholderColor: ColorSpec,
    val disabledPlaceholderColor: ColorSpec,
    val errorPlaceholderColor: ColorSpec,
    val focusedSupportingTextColor: ColorSpec,
    val unfocusedSupportingTextColor: ColorSpec,
    val disabledSupportingTextColor: ColorSpec,
    val errorSupportingTextColor: ColorSpec,
    val focusedPrefixColor: ColorSpec,
    val unfocusedPrefixColor: ColorSpec,
    val disabledPrefixColor: ColorSpec,
    val errorPrefixColor: ColorSpec,
    val focusedSuffixColor: ColorSpec,
    val unfocusedSuffixColor: ColorSpec,
    val disabledSuffixColor: ColorSpec,
    val errorSuffixColor: ColorSpec,
) {
    @Composable
    fun toTextFieldColors(): TextFieldColors {
        return TextFieldColors(
            focusedTextColor = focusedTextColor.value,
            unfocusedTextColor = unfocusedTextColor.value,
            disabledTextColor = disabledTextColor.value,
            errorTextColor = errorTextColor.value,
            focusedContainerColor = focusedContainerColor.value,
            unfocusedContainerColor = unfocusedContainerColor.value,
            disabledContainerColor = disabledContainerColor.value,
            errorContainerColor = errorContainerColor.value,
            cursorColor = cursorColor.value,
            errorCursorColor = errorCursorColor.value,
            textSelectionColors = textSelectionColors,
            focusedIndicatorColor = focusedIndicatorColor.value,
            unfocusedIndicatorColor = unfocusedIndicatorColor.value,
            disabledIndicatorColor = disabledIndicatorColor.value,
            errorIndicatorColor = errorIndicatorColor.value,
            focusedLeadingIconColor = focusedLeadingIconColor.value,
            unfocusedLeadingIconColor = unfocusedLeadingIconColor.value,
            disabledLeadingIconColor = disabledLeadingIconColor.value,
            errorLeadingIconColor = errorLeadingIconColor.value,
            focusedTrailingIconColor = focusedTrailingIconColor.value,
            unfocusedTrailingIconColor = unfocusedTrailingIconColor.value,
            disabledTrailingIconColor = disabledTrailingIconColor.value,
            errorTrailingIconColor = errorTrailingIconColor.value,
            focusedLabelColor = focusedLabelColor.value,
            unfocusedLabelColor = unfocusedLabelColor.value,
            disabledLabelColor = disabledLabelColor.value,
            errorLabelColor = errorLabelColor.value,
            focusedPlaceholderColor = focusedPlaceholderColor.value,
            unfocusedPlaceholderColor = unfocusedPlaceholderColor.value,
            disabledPlaceholderColor = disabledPlaceholderColor.value,
            errorPlaceholderColor = errorPlaceholderColor.value,
            focusedSupportingTextColor = focusedSupportingTextColor.value,
            unfocusedSupportingTextColor = unfocusedSupportingTextColor.value,
            disabledSupportingTextColor = disabledSupportingTextColor.value,
            errorSupportingTextColor = errorSupportingTextColor.value,
            focusedPrefixColor = focusedPrefixColor.value,
            unfocusedPrefixColor = unfocusedPrefixColor.value,
            disabledPrefixColor = disabledPrefixColor.value,
            errorPrefixColor = errorPrefixColor.value,
            focusedSuffixColor = focusedSuffixColor.value,
            unfocusedSuffixColor = unfocusedSuffixColor.value,
            disabledSuffixColor = disabledSuffixColor.value,
            errorSuffixColor = errorSuffixColor.value,
        )
    }
}