package com.zomato.sushi.compose.foundation.colorscheme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import com.zomato.sushi.compose.atoms.color.asColorSpec
import com.zomato.sushi.compose.foundation.SushiColorScheme
import com.zomato.sushi.compose.foundation.SushiColorSchemeType
import com.zomato.sushi.compose.foundation.SushiRawColorTokens

/**
 * Creates a light-themed color scheme for the Sushi design system.
 *
 * The function is designed to be used directly or as a base for more specialized theme variants.
 *
 * @author gupta.anirudh@zomato.com
 */
fun sushiLightColorScheme(
    materialColorScheme: ColorScheme = lightColorScheme(),
    themeColorScheme: SushiColorScheme.ThemeColorScheme,
    baseColorScheme: SushiColorScheme.BaseColorScheme,
    grey: SushiColorScheme.GreyColorScheme = SushiColorScheme.GreyColorScheme(),
    red: SushiColorScheme.RedColorScheme = SushiColorScheme.RedColorScheme(),
    green: SushiColorScheme.GreenColorScheme = SushiColorScheme.GreenColorScheme(),
    blue: SushiColorScheme.BlueColorScheme = SushiColorScheme.BlueColorScheme(),
    yellow: SushiColorScheme.YellowColorScheme = SushiColorScheme.YellowColorScheme(),
    purple: SushiColorScheme.PurpleColorScheme = SushiColorScheme.PurpleColorScheme(),
    indigo: SushiColorScheme.IndigoColorScheme = SushiColorScheme.IndigoColorScheme(),
    brown: SushiColorScheme.BrownColorScheme = SushiColorScheme.BrownColorScheme(),
    cider: SushiColorScheme.CiderColorScheme = SushiColorScheme.CiderColorScheme(),
    teal: SushiColorScheme.TealColorScheme = SushiColorScheme.TealColorScheme(),
    orange: SushiColorScheme.OrangeColorScheme = SushiColorScheme.OrangeColorScheme(),
    pink: SushiColorScheme.PinkColorScheme = SushiColorScheme.PinkColorScheme(),
    lime: SushiColorScheme.LimeColorScheme = SushiColorScheme.LimeColorScheme(),
    corn: SushiColorScheme.CornColorScheme = SushiColorScheme.CornColorScheme(),
    avacado: SushiColorScheme.AvacadoColorScheme = SushiColorScheme.AvacadoColorScheme(),
    gold: SushiColorScheme.GoldColorScheme = SushiColorScheme.GoldColorScheme(),
    onion: SushiColorScheme.OnionColorScheme = SushiColorScheme.OnionColorScheme(),
    charcoal: SushiColorScheme.CharcoalColorScheme = SushiColorScheme.CharcoalColorScheme(),
    honey: SushiColorScheme.HoneyColorScheme = SushiColorScheme.HoneyColorScheme(),
    tangerine: SushiColorScheme.TangerineColorScheme = SushiColorScheme.TangerineColorScheme(),
    slate: SushiColorScheme.SlateColorScheme = SushiColorScheme.SlateColorScheme(),
    rating: SushiColorScheme.RatingColorScheme = SushiColorScheme.RatingColorScheme(),
    textColorScheme: SushiColorScheme.TextColorScheme = SushiColorScheme.TextColorScheme(
        default = SushiRawColorTokens.Black.asColorSpec(),
        primary = SushiRawColorTokens.Grey900.asColorSpec(),
        secondary = SushiRawColorTokens.Grey700.asColorSpec(),
        tertiary = SushiRawColorTokens.Grey600.asColorSpec(),
        quaternary = SushiRawColorTokens.Grey500.asColorSpec(),
        disabled = SushiRawColorTokens.Grey400.asColorSpec(),
        inverse = SushiRawColorTokens.White.asColorSpec(),
        brand = themeColorScheme.v500,
        brandOnlyLight = themeColorScheme.v500,  // textBrand
        offer = SushiRawColorTokens.Blue500.asColorSpec(),
        success = SushiRawColorTokens.Green500.asColorSpec(),
        warning = SushiRawColorTokens.Yellow500.asColorSpec(),
        error = SushiRawColorTokens.Orange600.asColorSpec(),
        accentRed = SushiRawColorTokens.Red500.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red700.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange500.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange800.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green500.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green800.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue500.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue800.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple500.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple800.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow600.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow800.asColorSpec(),
        accentTeal = SushiRawColorTokens.Teal500.asColorSpec(),
        accentTealIntense = SushiRawColorTokens.Teal700.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider500.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider700.asColorSpec(),
        accentBrown = SushiRawColorTokens.Brown500.asColorSpec(),
        accentBrownIntense = SushiRawColorTokens.Brown700.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        light = SushiRawColorTokens.White.asColorSpec(),
        accentPink = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
        accentHoney = SushiRawColorTokens.Honey600.asColorSpec(),
        accentLime = SushiRawColorTokens.Lime700.asColorSpec(),
        accentLimeIntense = SushiRawColorTokens.Lime800.asColorSpec()
    ),
    iconColorScheme: SushiColorScheme.IconColorScheme = SushiColorScheme.IconColorScheme(
        default = SushiRawColorTokens.Black.asColorSpec(),
        primary = SushiRawColorTokens.Grey900.asColorSpec(),
        secondary = SushiRawColorTokens.Grey700.asColorSpec(),
        tertiary = SushiRawColorTokens.Grey600.asColorSpec(),
        quaternary = SushiRawColorTokens.Grey500.asColorSpec(),
        offer = SushiRawColorTokens.Blue500.asColorSpec(),
        warning = SushiRawColorTokens.Yellow500.asColorSpec(),
        error = SushiRawColorTokens.Orange600.asColorSpec(),
        success = SushiRawColorTokens.Green500.asColorSpec(),
        inverse = SushiRawColorTokens.White.asColorSpec(),
        brand = themeColorScheme.v500,
        disabled = SushiRawColorTokens.Grey400.asColorSpec(),
        brandOnlyLight = themeColorScheme.v500,
        accentOrange = SushiRawColorTokens.Orange500.asColorSpec(),
        accentRed = SushiRawColorTokens.Red500.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green500.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue500.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple500.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow400.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        light = SushiRawColorTokens.White.asColorSpec(),
        enable = SushiRawColorTokens.White.asColorSpec(),
        accentPink = SushiRawColorTokens.White.asColorSpec(),
        accentTeal = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
        accentLime = SushiRawColorTokens.Lime600.asColorSpec()
    ),
    surfaceColorScheme: SushiColorScheme.SurfaceColorScheme = SushiColorScheme.SurfaceColorScheme(
        backgroundPrimary = SushiRawColorTokens.White.asColorSpec(),
        backgroundSecondary = SushiRawColorTokens.Indigo050.asColorSpec(),
        primary = SushiRawColorTokens.White.asColorSpec(),
        secondary = SushiRawColorTokens.White.asColorSpec(),
        elevated = SushiRawColorTokens.Grey100.asColorSpec(),
        inverse = SushiRawColorTokens.Black.asColorSpec(),
        inset = SushiRawColorTokens.Grey050.asColorSpec(),
        insetIntense = SushiRawColorTokens.Grey100.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue050.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue100.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider050.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider100.asColorSpec(),
        disabled = SushiRawColorTokens.Grey500.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green050.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green100.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow050.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow100.asColorSpec(),
        accentRed = SushiRawColorTokens.Red050.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red100.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange050.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange100.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple050.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple100.asColorSpec(),
        accentBrown = SushiRawColorTokens.Brown050.asColorSpec(),
        accentBrownIntense = SushiRawColorTokens.Brown100.asColorSpec(),
        accentPink = SushiRawColorTokens.Pink050.asColorSpec(),
        accentPinkIntense = SushiRawColorTokens.Pink100.asColorSpec(),
        brandOnlylight = themeColorScheme.v500,
        brand = themeColorScheme.v500,
        selection = themeColorScheme.v050,
        success = SushiRawColorTokens.Green500.asColorSpec(),
        warning = SushiRawColorTokens.Yellow500.asColorSpec(),
        error = SushiRawColorTokens.Orange600.asColorSpec(),
        offer = SushiRawColorTokens.Blue500.asColorSpec(),
        shimmer = SushiRawColorTokens.Grey100.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        backgroundDark = SushiRawColorTokens.White.asColorSpec(),
        default = SushiRawColorTokens.White.asColorSpec(),
        deepened = SushiRawColorTokens.White.asColorSpec(),
        errorDark = SushiRawColorTokens.White.asColorSpec(),
        brandOnlyLight = SushiRawColorTokens.White.asColorSpec(),
        successDark = SushiRawColorTokens.White.asColorSpec(),
        accentGrey = SushiRawColorTokens.White.asColorSpec(),
        accentTangerine = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
        tertiary = SushiRawColorTokens.Charcoal100.asColorSpec(),
        quaternary = SushiRawColorTokens.Charcoal200.asColorSpec(),
        accentBlueOnly = SushiRawColorTokens.Blue900.asColorSpec(),
        accentBlueInverse = SushiRawColorTokens.Blue800.asColorSpec(),
        accentGreyInverse = SushiRawColorTokens.Charcoal800.asColorSpec(),
        accentTangerineIntense = SushiRawColorTokens.Tangerine200.asColorSpec(),
        accentTangerineInverse = SushiRawColorTokens.Tangerine900.asColorSpec(),
        accentIndigo = SushiRawColorTokens.Indigo100.asColorSpec(),
        accentIndigoIntense = SushiRawColorTokens.Indigo200.asColorSpec(),
        accentIndigoInverse = SushiRawColorTokens.Indigo900.asColorSpec(),
        darkIntense = SushiRawColorTokens.Black.asColorSpec(),
        accentTeal = SushiRawColorTokens.Teal100.asColorSpec(),
        backgroundSelection = themeColorScheme.v050,
        accentLime = SushiRawColorTokens.Lime050.asColorSpec(),
        accentLimeIntense = SushiRawColorTokens.Lime100.asColorSpec(),
    ),
    borderColorScheme: SushiColorScheme.BorderColorScheme = SushiColorScheme.BorderColorScheme(
        subtle = SushiRawColorTokens.Grey100.asColorSpec(),
        moderate = SushiRawColorTokens.Grey200.asColorSpec(),
        intense = SushiRawColorTokens.Grey200.asColorSpec(),
        inverse = SushiRawColorTokens.Slate600.asColorSpec(),
        selection = themeColorScheme.v500,
        brand = themeColorScheme.v500,
        success = SushiRawColorTokens.Green500.asColorSpec(),
        warning = SushiRawColorTokens.Yellow500.asColorSpec(),
        error = SushiRawColorTokens.Orange600.asColorSpec(),
        accentRed = SushiRawColorTokens.Red100.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red200.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow100.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow200.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider100.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider200.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple100.asColorSpec(),
        accentPink = SushiRawColorTokens.Pink100.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple200.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green100.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green200.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange100.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange200.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue100.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue200.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        dark = SushiRawColorTokens.White.asColorSpec(),
        accentWhite = SushiRawColorTokens.White.asColorSpec(),
        accentHoney = SushiRawColorTokens.Honey600.asColorSpec(),
        accentLime = SushiRawColorTokens.Lime200.asColorSpec(),
        accentLimeIntense = SushiRawColorTokens.Lime300.asColorSpec()
    ),
    crystalColorScheme: SushiColorScheme.CrystalColorScheme = SushiColorScheme.CrystalColorScheme(
        ontime = SushiRawColorTokens.Green600.asColorSpec(),
        delay = SushiRawColorTokens.White.asColorSpec(),
        rain = SushiRawColorTokens.Indigo500.asColorSpec(),
        polylineAerialCurved = SushiRawColorTokens.Black.asColorSpec(),
    ),
    dishColorScheme: SushiColorScheme.DishColorScheme = SushiColorScheme.DishColorScheme(
        background = SushiRawColorTokens.Yellow050.asColorSpec(),
        border = SushiRawColorTokens.Yellow200.asColorSpec(),
        icon = SushiRawColorTokens.Yellow400.asColorSpec(),
    ),
    resColorScheme: SushiColorScheme.ResColorScheme = SushiColorScheme.ResColorScheme(
        background50 = SushiRawColorTokens.Green800.asColorSpec(),
        background45 = SushiRawColorTokens.Green700.asColorSpec(),
        background40 = SushiRawColorTokens.Green600.asColorSpec(),
        background35 = SushiRawColorTokens.Green500.asColorSpec(),
        background30 = SushiRawColorTokens.Yellow400.asColorSpec(),
        background25 = SushiRawColorTokens.Orange400.asColorSpec(),
        background20 = SushiRawColorTokens.Orange400.asColorSpec(),
        background15 = SushiRawColorTokens.Orange400.asColorSpec(),
        background00 = SushiRawColorTokens.Grey500.asColorSpec(),
        backgroundNew = SushiRawColorTokens.Green100.asColorSpec(),
        borderNew = SushiRawColorTokens.Green300.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelNew = SushiRawColorTokens.Green600.asColorSpec(),
    ),
    buttonColorScheme: SushiColorScheme.ButtonColorScheme = SushiColorScheme.ButtonColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundPressed = themeColorScheme.v600,
        primaryBackgroundDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
        backgroundDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
        primaryLabel = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelPressed = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryIcon = SushiRawColorTokens.White.asColorSpec(),
        primaryIconPressed = SushiRawColorTokens.White.asColorSpec(),
        primaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        secondaryBackground = SushiRawColorTokens.Transparent.asColorSpec(),    // ctodo: revert to themeColorScheme.v500 ?,
        secondaryBackgroundPressed = SushiRawColorTokens.Transparent.asColorSpec(),    // ctodo: revert to themeColorScheme.v600 ?
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelPressed = themeColorScheme.v600,  // ctodo: revert to SushiWhite.asColorSpec(),
        secondaryLabelDisabled = SushiRawColorTokens.Grey400.asColorSpec(), // ctodo: revert to SushiGrey050.asColorSpec() ?
        secondaryIcon = themeColorScheme.v500,
        secondaryIconPressed = themeColorScheme.v600,
        secondaryIconDisabled = iconColorScheme.disabled,
        ghostBackground = SushiRawColorTokens.Transparent.asColorSpec(),    // ctodo: revert to themeColorScheme.v500 ?,
        ghostBackgroundPressed = SushiRawColorTokens.Transparent.asColorSpec(),   // ctodo: revert to themeColorScheme.v600,
        ghostLabel = themeColorScheme.v500, //  ctodo: revert to SushiGrey400 ?,
        ghostLabelPressed = themeColorScheme.v600, // ctodo: revert to themeColorScheme.accentColor ?,
        ghostLabelDisabled = textColorScheme.disabled,   // ctodo: revert to themeColorScheme.v600 ?,
        ghostIcon = themeColorScheme.v500,
        ghostIconPressed = themeColorScheme.v600,
        ghostIconDisabled = iconColorScheme.disabled,
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderPressed = themeColorScheme.v600,
        secondaryBorderDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        tertiaryBackground = SushiRawColorTokens.White.asColorSpec(),
        tertiaryBackgroundPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabel = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabelPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIcon = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIconPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStroke = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStrokePressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStrokeDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    stepperColorScheme: SushiColorScheme.StepperColorScheme = SushiColorScheme.StepperColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
        primaryIcon = SushiRawColorTokens.White.asColorSpec(),
        primaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryLabel = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBackground = themeColorScheme.v050,
        secondaryBackgroundDisabled = SushiRawColorTokens.Grey100.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
        secondaryLabelNumber = textColorScheme.primary,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
        secondaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderDisabled = SushiRawColorTokens.Grey400.asColorSpec(),
    ),
    shimmerColorScheme: SushiColorScheme.ShimmerColorScheme = SushiColorScheme.ShimmerColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        start = SushiRawColorTokens.White.asColorSpec(),
        end = SushiRawColorTokens.White.asColorSpec(),
    ),
    sliderColorScheme: SushiColorScheme.SliderColorScheme = SushiColorScheme.SliderColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        background = SushiRawColorTokens.White.asColorSpec(),
        backgroundPressed = SushiRawColorTokens.White.asColorSpec(),
        backgroundDisabled = SushiRawColorTokens.White.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelPressed = SushiRawColorTokens.White.asColorSpec(),
        labelDisabled = SushiRawColorTokens.White.asColorSpec(),
        labelComplete = SushiRawColorTokens.White.asColorSpec(),
        icon = SushiRawColorTokens.White.asColorSpec(),
        iconPressed = SushiRawColorTokens.White.asColorSpec(),
        iconDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    filterColorScheme: SushiColorScheme.FilterColorScheme = SushiColorScheme.FilterColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        backgroundSuccess = SushiRawColorTokens.White.asColorSpec(),
        stroke = SushiRawColorTokens.White.asColorSpec(),
        strokeSuccess = SushiRawColorTokens.White.asColorSpec(),
        strokeDisabled = SushiRawColorTokens.White.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelDisabled = SushiRawColorTokens.White.asColorSpec(),
        icon = SushiRawColorTokens.White.asColorSpec(),
        iconDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    aeroBarColorScheme: SushiColorScheme.AerobarColorScheme = SushiColorScheme.AerobarColorScheme(
        default = SushiRawColorTokens.Charcoal900.asColorSpec(),
        success = SushiRawColorTokens.Green600.asColorSpec(),
        error = SushiRawColorTokens.Tangerine600.asColorSpec(),
        warning = SushiRawColorTokens.Honey300.asColorSpec(),
        discover = SushiRawColorTokens.Blue500.asColorSpec(),
        accentDefault = SushiRawColorTokens.Charcoal050.asColorSpec(),
        accentSuccess = SushiRawColorTokens.Green100.asColorSpec(),
        accentWarning = SushiRawColorTokens.Honey100.asColorSpec(),
        accentError = SushiRawColorTokens.Tangerine100.asColorSpec(),
        accentDiscover = SushiRawColorTokens.Blue100.asColorSpec(),
    ),
    tagColorScheme: SushiColorScheme.TagColorScheme = SushiColorScheme.TagColorScheme(
        primaryBlack = SushiRawColorTokens.Black.asColorSpec(),
        primaryGrey = SushiRawColorTokens.Charcoal700.asColorSpec(),
        primaryGreen = SushiRawColorTokens.Green600.asColorSpec(),
        primaryPurple = SushiRawColorTokens.Purple600.asColorSpec(),
        primaryTeal = SushiRawColorTokens.Teal600.asColorSpec(),
        primaryPink = SushiRawColorTokens.Pink700.asColorSpec(),
        primaryYellow = SushiRawColorTokens.Honey300.asColorSpec(),
        primaryOrange = SushiRawColorTokens.Tangerine600.asColorSpec(),
        primaryBlue = SushiRawColorTokens.Blue600.asColorSpec(),
        secondaryGrey = SushiRawColorTokens.Charcoal100.asColorSpec(),
        secondaryGreen = SushiRawColorTokens.Green100.asColorSpec(),
        secondaryPurple = SushiRawColorTokens.Purple100.asColorSpec(),
        secondaryTeal = SushiRawColorTokens.Teal100.asColorSpec(),
        secondaryPink = SushiRawColorTokens.Pink100.asColorSpec(),
        secondaryYellow = SushiRawColorTokens.Honey050.asColorSpec(),
        secondaryOrange = SushiRawColorTokens.Tangerine100.asColorSpec(),
        secondaryBlue = SushiRawColorTokens.Blue050.asColorSpec(),
    )
): SushiColorScheme =
    SushiColorScheme(
        schemeType = SushiColorSchemeType.Light,
        material = materialColorScheme,
        grey = grey,
        red = red,
        green = green,
        blue = blue,
        yellow = yellow,
        purple = purple,
        indigo = indigo,
        brown = brown,
        cider = cider,
        teal = teal,
        orange = orange,
        pink = pink,
        lime = lime,
        corn = corn,
        avacado = avacado,
        gold = gold,
        onion = onion,
        charcoal = charcoal,
        honey = honey,
        tangerine = tangerine,
        slate = slate,
        rating = rating,
        theme = themeColorScheme,
        base = baseColorScheme,
        text = textColorScheme,
        icon = iconColorScheme,
        surface = surfaceColorScheme,
        border = borderColorScheme,
        crystal = crystalColorScheme,
        dish = dishColorScheme,
        res = resColorScheme,
        button = buttonColorScheme,
        stepper = stepperColorScheme,
        shimmer = shimmerColorScheme,
        slider = sliderColorScheme,
        filter = filterColorScheme,
        aerobar = aeroBarColorScheme,
        tag = tagColorScheme,
    )

/**
 * Creates a dark-themed color scheme for the Sushi design system.
 *
 * The function is designed to be used directly or as a base for more specialized theme variants.
 *
 * @author gupta.anirudh@zomato.com
 */
fun sushiDarkColorScheme(
    materialColorScheme: ColorScheme = darkColorScheme(),
    themeColorScheme: SushiColorScheme.ThemeColorScheme,
    baseColorScheme: SushiColorScheme.BaseColorScheme,
    grey: SushiColorScheme.GreyColorScheme = SushiColorScheme.GreyColorScheme(),
    red: SushiColorScheme.RedColorScheme = SushiColorScheme.RedColorScheme(),
    green: SushiColorScheme.GreenColorScheme = SushiColorScheme.GreenColorScheme(),
    blue: SushiColorScheme.BlueColorScheme = SushiColorScheme.BlueColorScheme(),
    yellow: SushiColorScheme.YellowColorScheme = SushiColorScheme.YellowColorScheme(),
    purple: SushiColorScheme.PurpleColorScheme = SushiColorScheme.PurpleColorScheme(),
    indigo: SushiColorScheme.IndigoColorScheme = SushiColorScheme.IndigoColorScheme(),
    brown: SushiColorScheme.BrownColorScheme = SushiColorScheme.BrownColorScheme(),
    cider: SushiColorScheme.CiderColorScheme = SushiColorScheme.CiderColorScheme(),
    teal: SushiColorScheme.TealColorScheme = SushiColorScheme.TealColorScheme(),
    orange: SushiColorScheme.OrangeColorScheme = SushiColorScheme.OrangeColorScheme(),
    pink: SushiColorScheme.PinkColorScheme = SushiColorScheme.PinkColorScheme(),
    lime: SushiColorScheme.LimeColorScheme = SushiColorScheme.LimeColorScheme(),
    corn: SushiColorScheme.CornColorScheme = SushiColorScheme.CornColorScheme(),
    avacado: SushiColorScheme.AvacadoColorScheme = SushiColorScheme.AvacadoColorScheme(),
    gold: SushiColorScheme.GoldColorScheme = SushiColorScheme.GoldColorScheme(),
    onion: SushiColorScheme.OnionColorScheme = SushiColorScheme.OnionColorScheme(),
    charcoal: SushiColorScheme.CharcoalColorScheme = SushiColorScheme.CharcoalColorScheme(),
    honey: SushiColorScheme.HoneyColorScheme = SushiColorScheme.HoneyColorScheme(),
    tangerine: SushiColorScheme.TangerineColorScheme = SushiColorScheme.TangerineColorScheme(),
    slate: SushiColorScheme.SlateColorScheme = SushiColorScheme.SlateColorScheme(),
    rating: SushiColorScheme.RatingColorScheme = SushiColorScheme.RatingColorScheme(),
    textColorScheme: SushiColorScheme.TextColorScheme = SushiColorScheme.TextColorScheme(
        default = SushiRawColorTokens.Slate050.asColorSpec(),
        primary = SushiRawColorTokens.Slate100.asColorSpec(),
        secondary = SushiRawColorTokens.Slate300.asColorSpec(),
        tertiary = SushiRawColorTokens.Slate400.asColorSpec(),
        quaternary = SushiRawColorTokens.Slate500.asColorSpec(),
        disabled = SushiRawColorTokens.Slate600.asColorSpec(),
        inverse = SushiRawColorTokens.Slate900.asColorSpec(),
        brand = themeColorScheme.v500,
        brandOnlyLight = SushiRawColorTokens.Slate100.asColorSpec(),  // textPrimary
        offer = SushiRawColorTokens.Blue300.asColorSpec(),
        success = SushiRawColorTokens.Green300.asColorSpec(),
        warning = SushiRawColorTokens.Yellow300.asColorSpec(),
        error = SushiRawColorTokens.Orange300.asColorSpec(),
        accentRed = SushiRawColorTokens.Red200.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red100.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange200.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange100.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green200.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green100.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue200.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue100.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple200.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple100.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow100.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow050.asColorSpec(),
        accentTeal = SushiRawColorTokens.Teal200.asColorSpec(),
        accentTealIntense = SushiRawColorTokens.Teal100.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider200.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider100.asColorSpec(),
        accentBrown = SushiRawColorTokens.Brown200.asColorSpec(),
        accentBrownIntense = SushiRawColorTokens.Brown100.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        light = SushiRawColorTokens.White.asColorSpec(),
        accentPink = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
        accentHoney = SushiRawColorTokens.Honey700.asColorSpec(),
        accentLime = SushiRawColorTokens.Lime200.asColorSpec(),
        accentLimeIntense = SushiRawColorTokens.Lime100.asColorSpec()
    ),
    iconColorScheme: SushiColorScheme.IconColorScheme = SushiColorScheme.IconColorScheme(
        default = SushiRawColorTokens.Slate050.asColorSpec(),
        primary = SushiRawColorTokens.Slate100.asColorSpec(),
        secondary = SushiRawColorTokens.Slate300.asColorSpec(),
        tertiary = SushiRawColorTokens.Slate400.asColorSpec(),
        quaternary = SushiRawColorTokens.Slate500.asColorSpec(),
        offer = SushiRawColorTokens.Blue300.asColorSpec(),
        warning = SushiRawColorTokens.Yellow300.asColorSpec(),
        error = SushiRawColorTokens.Orange300.asColorSpec(),
        success = SushiRawColorTokens.Green700.asColorSpec(),
        inverse = SushiRawColorTokens.Slate900.asColorSpec(),
        brand = themeColorScheme.v500,
        disabled = SushiRawColorTokens.Slate600.asColorSpec(),
        brandOnlyLight = SushiRawColorTokens.Slate100.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange400.asColorSpec(),
        accentRed = SushiRawColorTokens.Red400.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green400.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue400.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple400.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow300.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        light = SushiRawColorTokens.White.asColorSpec(),
        enable = SushiRawColorTokens.White.asColorSpec(),
        accentPink = SushiRawColorTokens.White.asColorSpec(),
        accentTeal = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
        accentLime = SushiRawColorTokens.Lime400.asColorSpec()
    ),
    surfaceColorScheme: SushiColorScheme.SurfaceColorScheme = SushiColorScheme.SurfaceColorScheme(
        backgroundPrimary = SushiRawColorTokens.Slate900.asColorSpec(),
        backgroundSecondary = SushiRawColorTokens.Slate900.asColorSpec(),
        primary = SushiRawColorTokens.Slate800.asColorSpec(),
        secondary = SushiRawColorTokens.Slate700.asColorSpec(),
        elevated = SushiRawColorTokens.Slate700.asColorSpec(),
        inverse = SushiRawColorTokens.Slate050.asColorSpec(),
        inset = SushiRawColorTokens.Slate800.asColorSpec(),
        insetIntense = SushiRawColorTokens.Slate700.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue900.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue900.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider900.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider900.asColorSpec(),
        disabled = SushiRawColorTokens.Slate600.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green900.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green900.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow900.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow900.asColorSpec(),
        accentRed = SushiRawColorTokens.Red900.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red900.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange900.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange900.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple900.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple900.asColorSpec(),
        accentBrown = SushiRawColorTokens.Brown900.asColorSpec(),
        accentBrownIntense = SushiRawColorTokens.Brown900.asColorSpec(),
        accentPink = SushiRawColorTokens.Pink900.asColorSpec(),
        accentPinkIntense = SushiRawColorTokens.Pink900.asColorSpec(),
        brandOnlylight = SushiRawColorTokens.Slate050.asColorSpec(),
        brand = themeColorScheme.v500,
        selection = themeColorScheme.v050,
        success = SushiRawColorTokens.Green500.asColorSpec(),
        warning = SushiRawColorTokens.Yellow800.asColorSpec(),
        error = SushiRawColorTokens.Orange800.asColorSpec(),
        offer = SushiRawColorTokens.Blue500.asColorSpec(),
        shimmer = SushiRawColorTokens.Slate700.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        backgroundDark = SushiRawColorTokens.White.asColorSpec(),
        default = SushiRawColorTokens.White.asColorSpec(),
        deepened = SushiRawColorTokens.White.asColorSpec(),
        errorDark = SushiRawColorTokens.White.asColorSpec(),
        brandOnlyLight = SushiRawColorTokens.White.asColorSpec(),
        successDark = SushiRawColorTokens.White.asColorSpec(),
        accentGrey = SushiRawColorTokens.White.asColorSpec(),
        accentTangerine = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
        tertiary = SushiRawColorTokens.Charcoal800.asColorSpec(),
        quaternary = SushiRawColorTokens.Charcoal700.asColorSpec(),
        accentBlueOnly = SushiRawColorTokens.Blue900.asColorSpec(),
        accentBlueInverse = SushiRawColorTokens.Blue100.asColorSpec(),
        accentGreyInverse = SushiRawColorTokens.Charcoal100.asColorSpec(),
        accentTangerineIntense = SushiRawColorTokens.Tangerine700.asColorSpec(),
        accentTangerineInverse = SushiRawColorTokens.Tangerine050.asColorSpec(),
        accentIndigo = SushiRawColorTokens.Indigo800.asColorSpec(),
        accentIndigoIntense = SushiRawColorTokens.Indigo700.asColorSpec(),
        accentIndigoInverse = SushiRawColorTokens.Indigo050.asColorSpec(),
        darkIntense = SushiRawColorTokens.Black.asColorSpec(),
        accentTeal = SushiRawColorTokens.Teal900.asColorSpec(),
        backgroundSelection = themeColorScheme.v050,
        accentLime = SushiRawColorTokens.Lime900.asColorSpec(),
        accentLimeIntense = SushiRawColorTokens.Lime900.asColorSpec()
    ),
    borderColorScheme: SushiColorScheme.BorderColorScheme = SushiColorScheme.BorderColorScheme(
        subtle = SushiRawColorTokens.Slate800.asColorSpec(),
        moderate = SushiRawColorTokens.Slate700.asColorSpec(),
        intense = SushiRawColorTokens.Slate600.asColorSpec(),
        inverse = SushiRawColorTokens.Slate200.asColorSpec(),
        selection = themeColorScheme.v100,
        brand = themeColorScheme.v300,
        success = SushiRawColorTokens.Green300.asColorSpec(),
        warning = SushiRawColorTokens.Yellow300.asColorSpec(),
        error = SushiRawColorTokens.Orange300.asColorSpec(),
        accentRed = SushiRawColorTokens.Red800.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red700.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow800.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow700.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider800.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider700.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple800.asColorSpec(),
        accentPink = SushiRawColorTokens.Pink800.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple700.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green800.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green700.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange800.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange700.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue800.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue700.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        dark = SushiRawColorTokens.White.asColorSpec(),
        accentHoney = SushiRawColorTokens.Honey300.asColorSpec(),
        accentWhite = SushiRawColorTokens.White.asColorSpec(),
        accentLime = SushiRawColorTokens.Lime800.asColorSpec(),
        accentLimeIntense =  SushiRawColorTokens.Lime700.asColorSpec()
    ),
    crystalColorScheme: SushiColorScheme.CrystalColorScheme = SushiColorScheme.CrystalColorScheme(
        ontime = SushiRawColorTokens.Green800.asColorSpec(),
        delay = SushiRawColorTokens.Slate800.asColorSpec(),
        rain = SushiRawColorTokens.Indigo800.asColorSpec(),
        polylineAerialCurved = SushiRawColorTokens.Slate200.asColorSpec(),
    ),
    dishColorScheme: SushiColorScheme.DishColorScheme = SushiColorScheme.DishColorScheme(
        background = surfaceColorScheme.secondary,
        border = borderColorScheme.intense,
        icon = SushiRawColorTokens.Yellow200.asColorSpec(),
    ),
    resColorScheme: SushiColorScheme.ResColorScheme = SushiColorScheme.ResColorScheme(
        background50 = SushiRawColorTokens.Green800.asColorSpec(),
        background45 = SushiRawColorTokens.Green700.asColorSpec(),
        background40 = SushiRawColorTokens.Green600.asColorSpec(),
        background35 = SushiRawColorTokens.Green500.asColorSpec(),
        background30 = SushiRawColorTokens.Yellow500.asColorSpec(),
        background25 = SushiRawColorTokens.Orange400.asColorSpec(),
        background20 = SushiRawColorTokens.Orange400.asColorSpec(),
        background15 = SushiRawColorTokens.Orange400.asColorSpec(),
        background00 = SushiRawColorTokens.Slate500.asColorSpec(),
        backgroundNew = SushiRawColorTokens.Green800.asColorSpec(),
        borderNew = SushiRawColorTokens.Green600.asColorSpec(),
        label = SushiRawColorTokens.Slate100.asColorSpec(),
        labelNew = SushiRawColorTokens.Green200.asColorSpec(),
    ),
    buttonColorScheme: SushiColorScheme.ButtonColorScheme = SushiColorScheme.ButtonColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundPressed = themeColorScheme.v200,
        primaryBackgroundDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        backgroundDisabled = SushiRawColorTokens.Slate600.asColorSpec(),   // revert to SushiSlate600.asColorSpec() ?
        primaryLabel = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelPressed = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryIcon = SushiRawColorTokens.White.asColorSpec(),
        primaryIconPressed = SushiRawColorTokens.White.asColorSpec(),
        primaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        secondaryBackground = SushiRawColorTokens.Transparent.asColorSpec(), // ctodo: revert to themeColorScheme.v500,
        secondaryBackgroundPressed = themeColorScheme.v200, // ctodo: revert to themeColorScheme.v200,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelPressed = themeColorScheme.v200, // ctodo: revert to themeColorScheme.v200 ?,
        secondaryLabelDisabled = SushiRawColorTokens.Slate600.asColorSpec(), // ctodo: revert to SushiSlate400.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconPressed = themeColorScheme.v200,
        secondaryIconDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        ghostBackground = SushiRawColorTokens.Transparent.asColorSpec(), // ctodo: Revert to themeColorScheme.v500,
        ghostBackgroundPressed = SushiRawColorTokens.Transparent.asColorSpec(), // ctodo: revert to themeColorScheme.v200,
        ghostLabel = themeColorScheme.v500,
        ghostLabelPressed = themeColorScheme.v200,  // ctodo: revert to themeColorScheme.v200 ?
        ghostLabelDisabled = SushiRawColorTokens.Slate600.asColorSpec(), // ctodo: revert to SushiSlate600.asColorSpec(),
        ghostIcon = themeColorScheme.v500,
        ghostIconPressed = themeColorScheme.v200,
        ghostIconDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderPressed = themeColorScheme.v200, // ctodo: revert to themeColorScheme.v200 ?,
        secondaryBorderDisabled = SushiRawColorTokens.Slate600.asColorSpec(), // ctodo: revert to SushiSlate400.asColorSpec(),
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        tertiaryBackground = SushiRawColorTokens.White.asColorSpec(),
        tertiaryBackgroundPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabel = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabelPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIcon = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIconPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStroke = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStrokePressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStrokeDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    stepperColorScheme: SushiColorScheme.StepperColorScheme = SushiColorScheme.StepperColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        primaryIcon = SushiRawColorTokens.White.asColorSpec(),
        primaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryLabel = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBackground = themeColorScheme.v050,
        secondaryBackgroundDisabled = SushiRawColorTokens.Slate700.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconDisabled = SushiRawColorTokens.Slate500.asColorSpec(),
        secondaryLabelNumber = textColorScheme.primary,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelDisabled = SushiRawColorTokens.Slate500.asColorSpec(),
        secondaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBorder = themeColorScheme.v100,
        secondaryBorderDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
    ),
    shimmerColorScheme: SushiColorScheme.ShimmerColorScheme = SushiColorScheme.ShimmerColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        start = SushiRawColorTokens.White.asColorSpec(),
        end = SushiRawColorTokens.White.asColorSpec(),
    ),
    sliderColorScheme: SushiColorScheme.SliderColorScheme = SushiColorScheme.SliderColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        background = SushiRawColorTokens.White.asColorSpec(),
        backgroundPressed = SushiRawColorTokens.White.asColorSpec(),
        backgroundDisabled = SushiRawColorTokens.White.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelPressed = SushiRawColorTokens.White.asColorSpec(),
        labelDisabled = SushiRawColorTokens.White.asColorSpec(),
        labelComplete = SushiRawColorTokens.White.asColorSpec(),
        icon = SushiRawColorTokens.White.asColorSpec(),
        iconPressed = SushiRawColorTokens.White.asColorSpec(),
        iconDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    filterColorScheme: SushiColorScheme.FilterColorScheme = SushiColorScheme.FilterColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        backgroundSuccess = SushiRawColorTokens.White.asColorSpec(),
        stroke = SushiRawColorTokens.White.asColorSpec(),
        strokeSuccess = SushiRawColorTokens.White.asColorSpec(),
        strokeDisabled = SushiRawColorTokens.White.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelDisabled = SushiRawColorTokens.White.asColorSpec(),
        icon = SushiRawColorTokens.White.asColorSpec(),
        iconDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    aeroBarColorScheme: SushiColorScheme.AerobarColorScheme = SushiColorScheme.AerobarColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        default = SushiRawColorTokens.Charcoal900.asColorSpec(),
        success = SushiRawColorTokens.Green600.asColorSpec(),
        error = SushiRawColorTokens.Tangerine600.asColorSpec(),
        warning = SushiRawColorTokens.Honey300.asColorSpec(),
        discover = SushiRawColorTokens.Blue500.asColorSpec(),
        accentDefault = SushiRawColorTokens.Charcoal800.asColorSpec(),
        accentSuccess = SushiRawColorTokens.Green800.asColorSpec(),
        accentWarning = SushiRawColorTokens.Honey800.asColorSpec(),
        accentError = SushiRawColorTokens.Tangerine800.asColorSpec(),
        accentDiscover = SushiRawColorTokens.Blue900.asColorSpec(),
    ),
    tagColorScheme: SushiColorScheme.TagColorScheme = SushiColorScheme.TagColorScheme(
        // ctodo: Fix with actual values, after defaults are merged in View sushi.
        primaryBlack = SushiRawColorTokens.Charcoal100.asColorSpec(),
        primaryGrey = SushiRawColorTokens.Charcoal300.asColorSpec(),
        primaryGreen = SushiRawColorTokens.Green600.asColorSpec(),
        primaryPurple = SushiRawColorTokens.Purple400.asColorSpec(),
        primaryTeal = SushiRawColorTokens.Teal400.asColorSpec(),
        primaryPink = SushiRawColorTokens.Pink400.asColorSpec(),
        primaryYellow = SushiRawColorTokens.Honey200.asColorSpec(),
        primaryOrange = SushiRawColorTokens.Tangerine400.asColorSpec(),
        primaryBlue = SushiRawColorTokens.Blue500.asColorSpec(),
        secondaryGrey = SushiRawColorTokens.Charcoal800.asColorSpec(),
        secondaryGreen = SushiRawColorTokens.Green800.asColorSpec(),
        secondaryPurple = SushiRawColorTokens.Purple800.asColorSpec(),
        secondaryTeal = SushiRawColorTokens.Teal800.asColorSpec(),
        secondaryPink = SushiRawColorTokens.Pink800.asColorSpec(),
        secondaryYellow = SushiRawColorTokens.Honey800.asColorSpec(),
        secondaryOrange = SushiRawColorTokens.Tangerine800.asColorSpec(),
        secondaryBlue = SushiRawColorTokens.Blue800.asColorSpec(),
    )
): SushiColorScheme =
    SushiColorScheme(
        schemeType = SushiColorSchemeType.Dark,
        material = materialColorScheme,
        grey = grey,
        red = red,
        green = green,
        blue = blue,
        yellow = yellow,
        purple = purple,
        indigo = indigo,
        brown = brown,
        cider = cider,
        teal = teal,
        orange = orange,
        pink = pink,
        lime = lime,
        corn = corn,
        avacado = avacado,
        gold = gold,
        onion = onion,
        charcoal = charcoal,
        honey = honey,
        tangerine = tangerine,
        slate = slate,
        rating = rating,
        theme = themeColorScheme,
        base = baseColorScheme,
        text = textColorScheme,
        icon = iconColorScheme,
        surface = surfaceColorScheme,
        border = borderColorScheme,
        crystal = crystalColorScheme,
        dish = dishColorScheme,
        res = resColorScheme,
        button = buttonColorScheme,
        stepper = stepperColorScheme,
        shimmer = shimmerColorScheme,
        slider = sliderColorScheme,
        filter = filterColorScheme,
        aerobar = aeroBarColorScheme,
        tag = tagColorScheme,
    )