site_name: 'Sushi for Compose UI'
site_description: "Sushi UI is a comprehensive design system for Jetpack Compose that provides a rich set of customizable components for building beautiful, consistent, and accessible user interfaces."
site_url: https://zomato.com
docs_dir: 'docs'
site_dir: ../docs

repo_name: 'Compose-Sushi'
repo_url: https://github.com/Zomato/compose-sushi

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  favicon: assets/logo-site.png
  logo: assets/logo-site.png
  font:
    text: Fira Sans
    code: JetBrains Mono
  features:
    - navigation.sections
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    primary: custom

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Foundations:
      - Color Scheme: foundations/color-scheme.md
      - Typography: foundations/typography.md
      - Custom Theme: foundations/theme.md
  - Components:
      - 'SushiText': sushitext.md
      - 'SushiIcon': sushiicon.md
      - 'SushiButton': sushibutton.md
      - 'SushiImage': sushiimage.md
      - 'SushiCheckBox': sushicheckbox.md
      - 'SushiRadioButton': sushiradiobutton.md
      - 'SushiSwitch': sushiswitch.md
      - 'SushiTag': sushitag.md
      - 'SushiTextField': sushitextfield.md
      - 'SushiAnimation': sushianimation.md
      - 'SushiLoader': sushiloader.md
      - 'SushiCard': sushicard.md
      - 'SushiIndicator': sushiindicator.md
      - 'SushiDivider': sushidivider.md
      - 'SushiShimmer': sushishimmer.md
      - 'SushiSnackbar': sushisnackbar.md
      - 'SushiBottomSheet': sushibottomsheet.md
      - 'SushiDialog': sushidialog.md
      - 'SushiDropDown': sushidropdown.md
      - 'SushiMedia': sushimedia.md
      - 'SushiOTPInput': sushiotpinput.md
      - 'SushiHorizontalPager': sushihorizontalpager.md
      - 'SushiVerticalPager': sushiverticalpager.md
      - 'SushiRatingBar': sushiratingbar.md
      - 'SushiTooltip': sushitooltip.md
      - 'SushiViewFlipper': sushiviewflipper.md
  - Markdown:
      - Overview: markdown/overview.md
      - Customization: markdown/customization.md
  - Shapes:
      - Overview: shapes.md

plugins:
  - search

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.betterem
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  <a href="https://github.com/Zomato/compose-sushi">Copyright © 2025 Eternal Private Ltd.</a>