@file:OptIn(ExperimentalSushiApi::class)

package com.zomato.sushi.compose.foundation

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import com.zomato.sushi.compose.atoms.color.asColorSpec

/**
 * @author gupta.anirudh@zomato.com
 */
fun sushiDarkColorScheme(
    materialColorScheme: ColorScheme = darkColorScheme(),
    themeColorScheme: SushiColorScheme.ThemeColorScheme = SushiColorScheme.ThemeColorScheme(
        v050 = SushiRawColorTokens.Red050.asColorSpec(),
        v100 = SushiRawColorTokens.Red100.asColorSpec(),
        v200 = SushiRawColorTokens.Red200.asColorSpec(),
        v300 = SushiRawColorTokens.Red300.asColorSpec(),
        v400 = SushiRawColorTokens.Red400.asColorSpec(),
        v500 = SushiRawColorTokens.Red500.asColorSpec(),
        v600 = SushiRawColorTokens.Red600.asColorSpec(),
        v700 = SushiRawColorTokens.Red700.asColorSpec(),
        v800 = SushiRawColorTokens.Red800.asColorSpec(),
        v900 = SushiRawColorTokens.Red900.asColorSpec(),
        accentColor = SushiRawColorTokens.Red600.asColorSpec(),
    ),
    grey: SushiColorScheme.GreyColorScheme = SushiColorScheme.GreyColorScheme(
        v050 = SushiRawColorTokens.Grey900.asColorSpec(),
        v100 = SushiRawColorTokens.Grey800.asColorSpec(),
        v200 = SushiRawColorTokens.Grey700.asColorSpec(),
        v300 = SushiRawColorTokens.Grey600.asColorSpec(),
        v400 = SushiRawColorTokens.Grey500.asColorSpec(),
        v500 = SushiRawColorTokens.Grey400.asColorSpec(),
        v600 = SushiRawColorTokens.Grey300.asColorSpec(),
        v700 = SushiRawColorTokens.Grey200.asColorSpec(),
        v800 = SushiRawColorTokens.Grey100.asColorSpec(),
        v900 = SushiRawColorTokens.Grey050.asColorSpec(),
    ),
    red: SushiColorScheme.RedColorScheme = SushiColorScheme.RedColorScheme(
        v050 = SushiRawColorTokens.Red900.asColorSpec(),
        v100 = SushiRawColorTokens.Red800.asColorSpec(),
        v200 = SushiRawColorTokens.Red700.asColorSpec(),
        v300 = SushiRawColorTokens.Red600.asColorSpec(),
        v400 = SushiRawColorTokens.Red500.asColorSpec(),
        v500 = SushiRawColorTokens.Red400.asColorSpec(),
        v600 = SushiRawColorTokens.Red300.asColorSpec(),
        v700 = SushiRawColorTokens.Red200.asColorSpec(),
        v800 = SushiRawColorTokens.Red100.asColorSpec(),
        v900 = SushiRawColorTokens.Red050.asColorSpec(),
    ),
    green: SushiColorScheme.GreenColorScheme = SushiColorScheme.GreenColorScheme(
        v050 = SushiRawColorTokens.Green900.asColorSpec(),
        v100 = SushiRawColorTokens.Green800.asColorSpec(),
        v200 = SushiRawColorTokens.Green700.asColorSpec(),
        v300 = SushiRawColorTokens.Green600.asColorSpec(),
        v400 = SushiRawColorTokens.Green500.asColorSpec(),
        v500 = SushiRawColorTokens.Green400.asColorSpec(),
        v600 = SushiRawColorTokens.Green300.asColorSpec(),
        v700 = SushiRawColorTokens.Green200.asColorSpec(),
        v800 = SushiRawColorTokens.Green100.asColorSpec(),
        v900 = SushiRawColorTokens.Green050.asColorSpec(),
    ),
    blue: SushiColorScheme.BlueColorScheme = SushiColorScheme.BlueColorScheme(
        v050 = SushiRawColorTokens.Blue900.asColorSpec(),
        v100 = SushiRawColorTokens.Blue800.asColorSpec(),
        v200 = SushiRawColorTokens.Blue700.asColorSpec(),
        v300 = SushiRawColorTokens.Blue600.asColorSpec(),
        v400 = SushiRawColorTokens.Blue500.asColorSpec(),
        v500 = SushiRawColorTokens.Blue400.asColorSpec(),
        v600 = SushiRawColorTokens.Blue300.asColorSpec(),
        v700 = SushiRawColorTokens.Blue200.asColorSpec(),
        v800 = SushiRawColorTokens.Blue100.asColorSpec(),
        v900 = SushiRawColorTokens.Blue050.asColorSpec(),
    ),
    yellow: SushiColorScheme.YellowColorScheme = SushiColorScheme.YellowColorScheme(
        v050 = SushiRawColorTokens.Yellow900.asColorSpec(),
        v100 = SushiRawColorTokens.Yellow800.asColorSpec(),
        v200 = SushiRawColorTokens.Yellow700.asColorSpec(),
        v300 = SushiRawColorTokens.Yellow600.asColorSpec(),
        v400 = SushiRawColorTokens.Yellow500.asColorSpec(),
        v500 = SushiRawColorTokens.Yellow400.asColorSpec(),
        v600 = SushiRawColorTokens.Yellow300.asColorSpec(),
        v700 = SushiRawColorTokens.Yellow200.asColorSpec(),
        v800 = SushiRawColorTokens.Yellow100.asColorSpec(),
        v900 = SushiRawColorTokens.Yellow050.asColorSpec(),
    ),
    purple: SushiColorScheme.PurpleColorScheme = SushiColorScheme.PurpleColorScheme(
        v050 = SushiRawColorTokens.Purple900.asColorSpec(),
        v100 = SushiRawColorTokens.Purple800.asColorSpec(),
        v200 = SushiRawColorTokens.Purple700.asColorSpec(),
        v300 = SushiRawColorTokens.Purple600.asColorSpec(),
        v400 = SushiRawColorTokens.Purple500.asColorSpec(),
        v500 = SushiRawColorTokens.Purple400.asColorSpec(),
        v600 = SushiRawColorTokens.Purple300.asColorSpec(),
        v700 = SushiRawColorTokens.Purple200.asColorSpec(),
        v800 = SushiRawColorTokens.Purple100.asColorSpec(),
        v900 = SushiRawColorTokens.Purple050.asColorSpec(),
    ),
    indigo: SushiColorScheme.IndigoColorScheme = SushiColorScheme.IndigoColorScheme(
        v050 = SushiRawColorTokens.Indigo900.asColorSpec(),
        v100 = SushiRawColorTokens.Indigo800.asColorSpec(),
        v200 = SushiRawColorTokens.Indigo700.asColorSpec(),
        v300 = SushiRawColorTokens.Indigo600.asColorSpec(),
        v400 = SushiRawColorTokens.Indigo500.asColorSpec(),
        v500 = SushiRawColorTokens.Indigo400.asColorSpec(),
        v600 = SushiRawColorTokens.Indigo300.asColorSpec(),
        v700 = SushiRawColorTokens.Indigo200.asColorSpec(),
        v800 = SushiRawColorTokens.Indigo100.asColorSpec(),
        v900 = SushiRawColorTokens.Indigo050.asColorSpec(),
    ),
    brown: SushiColorScheme.BrownColorScheme = SushiColorScheme.BrownColorScheme(
        v050 = SushiRawColorTokens.Brown900.asColorSpec(),
        v100 = SushiRawColorTokens.Brown800.asColorSpec(),
        v200 = SushiRawColorTokens.Brown700.asColorSpec(),
        v300 = SushiRawColorTokens.Brown600.asColorSpec(),
        v400 = SushiRawColorTokens.Brown500.asColorSpec(),
        v500 = SushiRawColorTokens.Brown400.asColorSpec(),
        v600 = SushiRawColorTokens.Brown300.asColorSpec(),
        v700 = SushiRawColorTokens.Brown200.asColorSpec(),
        v800 = SushiRawColorTokens.Brown100.asColorSpec(),
        v900 = SushiRawColorTokens.Brown050.asColorSpec(),
    ),
    cider: SushiColorScheme.CiderColorScheme = SushiColorScheme.CiderColorScheme(
        v050 = SushiRawColorTokens.Cider900.asColorSpec(),
        v100 = SushiRawColorTokens.Cider800.asColorSpec(),
        v200 = SushiRawColorTokens.Cider700.asColorSpec(),
        v300 = SushiRawColorTokens.Cider600.asColorSpec(),
        v400 = SushiRawColorTokens.Cider500.asColorSpec(),
        v500 = SushiRawColorTokens.Cider400.asColorSpec(),
        v600 = SushiRawColorTokens.Cider300.asColorSpec(),
        v700 = SushiRawColorTokens.Cider200.asColorSpec(),
        v800 = SushiRawColorTokens.Cider100.asColorSpec(),
        v900 = SushiRawColorTokens.Cider050.asColorSpec(),
    ),
    teal: SushiColorScheme.TealColorScheme = SushiColorScheme.TealColorScheme(
        v050 = SushiRawColorTokens.Teal900.asColorSpec(),
        v100 = SushiRawColorTokens.Teal800.asColorSpec(),
        v200 = SushiRawColorTokens.Teal700.asColorSpec(),
        v300 = SushiRawColorTokens.Teal600.asColorSpec(),
        v400 = SushiRawColorTokens.Teal500.asColorSpec(),
        v500 = SushiRawColorTokens.Teal400.asColorSpec(),
        v600 = SushiRawColorTokens.Teal300.asColorSpec(),
        v700 = SushiRawColorTokens.Teal200.asColorSpec(),
        v800 = SushiRawColorTokens.Teal100.asColorSpec(),
        v900 = SushiRawColorTokens.Teal050.asColorSpec(),
    ),
    orange: SushiColorScheme.OrangeColorScheme = SushiColorScheme.OrangeColorScheme(
        v050 = SushiRawColorTokens.Orange900.asColorSpec(),
        v100 = SushiRawColorTokens.Orange800.asColorSpec(),
        v200 = SushiRawColorTokens.Orange700.asColorSpec(),
        v300 = SushiRawColorTokens.Orange600.asColorSpec(),
        v400 = SushiRawColorTokens.Orange500.asColorSpec(),
        v500 = SushiRawColorTokens.Orange400.asColorSpec(),
        v600 = SushiRawColorTokens.Orange300.asColorSpec(),
        v700 = SushiRawColorTokens.Orange200.asColorSpec(),
        v800 = SushiRawColorTokens.Orange100.asColorSpec(),
        v900 = SushiRawColorTokens.Orange050.asColorSpec(),
    ),
    pink: SushiColorScheme.PinkColorScheme = SushiColorScheme.PinkColorScheme(
        v050 = SushiRawColorTokens.Pink900.asColorSpec(),
        v100 = SushiRawColorTokens.Pink800.asColorSpec(),
        v200 = SushiRawColorTokens.Pink700.asColorSpec(),
        v300 = SushiRawColorTokens.Pink600.asColorSpec(),
        v400 = SushiRawColorTokens.Pink500.asColorSpec(),
        v500 = SushiRawColorTokens.Pink400.asColorSpec(),
        v600 = SushiRawColorTokens.Pink300.asColorSpec(),
        v700 = SushiRawColorTokens.Pink200.asColorSpec(),
        v800 = SushiRawColorTokens.Pink100.asColorSpec(),
        v900 = SushiRawColorTokens.Pink050.asColorSpec(),
    ),
    lime: SushiColorScheme.LimeColorScheme = SushiColorScheme.LimeColorScheme(
        v050 = SushiRawColorTokens.Lime900.asColorSpec(),
        v100 = SushiRawColorTokens.Lime800.asColorSpec(),
        v200 = SushiRawColorTokens.Lime700.asColorSpec(),
        v300 = SushiRawColorTokens.Lime600.asColorSpec(),
        v400 = SushiRawColorTokens.Lime500.asColorSpec(),
        v500 = SushiRawColorTokens.Lime400.asColorSpec(),
        v600 = SushiRawColorTokens.Lime300.asColorSpec(),
        v700 = SushiRawColorTokens.Lime200.asColorSpec(),
        v800 = SushiRawColorTokens.Lime100.asColorSpec(),
        v900 = SushiRawColorTokens.Lime050.asColorSpec(),
    ),
    corn: SushiColorScheme.CornColorScheme = SushiColorScheme.CornColorScheme(),
    avacado: SushiColorScheme.AvacadoColorScheme = SushiColorScheme.AvacadoColorScheme(),
    gold: SushiColorScheme.GoldColorScheme = SushiColorScheme.GoldColorScheme(),
    onion: SushiColorScheme.OnionColorScheme = SushiColorScheme.OnionColorScheme(
        v050 = SushiRawColorTokens.Onion900.asColorSpec(),
        v100 = SushiRawColorTokens.Onion800.asColorSpec(),
        v200 = SushiRawColorTokens.Onion700.asColorSpec(),
        v300 = SushiRawColorTokens.Onion600.asColorSpec(),
        v400 = SushiRawColorTokens.Onion500.asColorSpec(),
        v500 = SushiRawColorTokens.Onion400.asColorSpec(),
        v600 = SushiRawColorTokens.Onion300.asColorSpec(),
        v700 = SushiRawColorTokens.Onion200.asColorSpec(),
        v800 = SushiRawColorTokens.Onion100.asColorSpec(),
        v900 = SushiRawColorTokens.Onion050.asColorSpec(),
    ),
    charcoal: SushiColorScheme.CharcoalColorScheme = SushiColorScheme.CharcoalColorScheme(
        v050 = SushiRawColorTokens.Charcoal900.asColorSpec(),
        v100 = SushiRawColorTokens.Charcoal800.asColorSpec(),
        v200 = SushiRawColorTokens.Charcoal700.asColorSpec(),
        v300 = SushiRawColorTokens.Charcoal600.asColorSpec(),
        v400 = SushiRawColorTokens.Charcoal500.asColorSpec(),
        v500 = SushiRawColorTokens.Charcoal400.asColorSpec(),
        v600 = SushiRawColorTokens.Charcoal300.asColorSpec(),
        v700 = SushiRawColorTokens.Charcoal200.asColorSpec(),
        v800 = SushiRawColorTokens.Charcoal100.asColorSpec(),
        v900 = SushiRawColorTokens.Charcoal050.asColorSpec(),
    ),
    honey: SushiColorScheme.HoneyColorScheme = SushiColorScheme.HoneyColorScheme(
        v050 = SushiRawColorTokens.Honey900.asColorSpec(),
        v100 = SushiRawColorTokens.Honey800.asColorSpec(),
        v200 = SushiRawColorTokens.Honey700.asColorSpec(),
        v300 = SushiRawColorTokens.Honey600.asColorSpec(),
        v400 = SushiRawColorTokens.Honey500.asColorSpec(),
        v500 = SushiRawColorTokens.Honey400.asColorSpec(),
        v600 = SushiRawColorTokens.Honey300.asColorSpec(),
        v700 = SushiRawColorTokens.Honey200.asColorSpec(),
        v800 = SushiRawColorTokens.Honey100.asColorSpec(),
        v900 = SushiRawColorTokens.Honey050.asColorSpec(),
    ),
    tangerine: SushiColorScheme.TangerineColorScheme = SushiColorScheme.TangerineColorScheme(
        v050 = SushiRawColorTokens.Tangerine900.asColorSpec(),
        v100 = SushiRawColorTokens.Tangerine800.asColorSpec(),
        v200 = SushiRawColorTokens.Tangerine700.asColorSpec(),
        v300 = SushiRawColorTokens.Tangerine600.asColorSpec(),
        v400 = SushiRawColorTokens.Tangerine500.asColorSpec(),
        v500 = SushiRawColorTokens.Tangerine400.asColorSpec(),
        v600 = SushiRawColorTokens.Tangerine300.asColorSpec(),
        v700 = SushiRawColorTokens.Tangerine200.asColorSpec(),
        v800 = SushiRawColorTokens.Tangerine100.asColorSpec(),
        v900 = SushiRawColorTokens.Tangerine050.asColorSpec(),
    ),
    slate: SushiColorScheme.SlateColorScheme = SushiColorScheme.SlateColorScheme(
        v050 = SushiRawColorTokens.Slate900.asColorSpec(),
        v100 = SushiRawColorTokens.Slate800.asColorSpec(),
        v200 = SushiRawColorTokens.Slate700.asColorSpec(),
        v300 = SushiRawColorTokens.Slate600.asColorSpec(),
        v400 = SushiRawColorTokens.Slate500.asColorSpec(),
        v500 = SushiRawColorTokens.Slate400.asColorSpec(),
        v600 = SushiRawColorTokens.Slate300.asColorSpec(),
        v700 = SushiRawColorTokens.Slate200.asColorSpec(),
        v800 = SushiRawColorTokens.Slate100.asColorSpec(),
        v900 = SushiRawColorTokens.Slate050.asColorSpec(),
    ),
    rating: SushiColorScheme.RatingColorScheme = SushiColorScheme.RatingColorScheme(
        one = SushiRawColorTokens.Red300.asColorSpec(),
        two = SushiRawColorTokens.Yellow200.asColorSpec(),
        three = SushiRawColorTokens.Lime400.asColorSpec(),
        four = SushiRawColorTokens.Lime200.asColorSpec(),
        five = SushiRawColorTokens.Lime050.asColorSpec(),
        unchecked = SushiRawColorTokens.Slate400.asColorSpec(),
    ),
    textColorScheme: SushiColorScheme.TextColorScheme = SushiColorScheme.TextColorScheme(
        default = SushiRawColorTokens.Slate050.asColorSpec(),
        primary = SushiRawColorTokens.Slate100.asColorSpec(),
        secondary = SushiRawColorTokens.Slate300.asColorSpec(),
        tertiary = SushiRawColorTokens.Slate400.asColorSpec(),
        quaternary = SushiRawColorTokens.Slate500.asColorSpec(),
        disabled = SushiRawColorTokens.Slate600.asColorSpec(),
        inverse = SushiRawColorTokens.Slate900.asColorSpec(),
        brand = themeColorScheme.v500,
        brandOnlyLight = SushiRawColorTokens.Slate100.asColorSpec(),  // textPrimary
        offer = SushiRawColorTokens.Blue300.asColorSpec(),
        success = SushiRawColorTokens.Green300.asColorSpec(),
        warning = SushiRawColorTokens.Yellow300.asColorSpec(),
        error = SushiRawColorTokens.Orange300.asColorSpec(),
        accentRed = SushiRawColorTokens.Red200.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red100.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange200.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange100.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green200.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green100.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue200.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue100.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple200.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple100.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow100.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow050.asColorSpec(),
        accentTeal = SushiRawColorTokens.Teal200.asColorSpec(),
        accentTealIntense = SushiRawColorTokens.Teal100.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider200.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider100.asColorSpec(),
        accentBrown = SushiRawColorTokens.Brown200.asColorSpec(),
        accentBrownIntense = SushiRawColorTokens.Brown100.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        light = SushiRawColorTokens.White.asColorSpec(),
        accentPink = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
    ),
    iconColorScheme: SushiColorScheme.IconColorScheme = SushiColorScheme.IconColorScheme(
        default = SushiRawColorTokens.Slate050.asColorSpec(),
        primary = SushiRawColorTokens.Slate100.asColorSpec(),
        secondary = SushiRawColorTokens.Slate300.asColorSpec(),
        tertiary = SushiRawColorTokens.Slate400.asColorSpec(),
        quaternary = SushiRawColorTokens.Slate500.asColorSpec(),
        offer = SushiRawColorTokens.Blue300.asColorSpec(),
        warning = SushiRawColorTokens.Yellow300.asColorSpec(),
        error = SushiRawColorTokens.Orange300.asColorSpec(),
        success = SushiRawColorTokens.Green700.asColorSpec(),
        inverse = SushiRawColorTokens.Slate900.asColorSpec(),
        brand = themeColorScheme.v500,
        disabled = SushiRawColorTokens.Slate100.asColorSpec(),
        brandOnlyLight = SushiRawColorTokens.Slate600.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange400.asColorSpec(),
        accentRed = SushiRawColorTokens.Red400.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green400.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue400.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple400.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow300.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        light = SushiRawColorTokens.White.asColorSpec(),
        enable = SushiRawColorTokens.White.asColorSpec(),
        accentPink = SushiRawColorTokens.White.asColorSpec(),
        accentTeal = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
    ),
    surfaceColorScheme: SushiColorScheme.SurfaceColorScheme = SushiColorScheme.SurfaceColorScheme(
        backgroundPrimary = SushiRawColorTokens.Slate900.asColorSpec(),
        backgroundSecondary = SushiRawColorTokens.Slate900.asColorSpec(),
        primary = SushiRawColorTokens.Slate800.asColorSpec(),
        secondary = SushiRawColorTokens.Slate700.asColorSpec(),
        elevated = SushiRawColorTokens.Slate700.asColorSpec(),
        inverse = SushiRawColorTokens.Slate050.asColorSpec(),
        inset = SushiRawColorTokens.Slate800.asColorSpec(),
        insetIntense = SushiRawColorTokens.Slate700.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue900.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue900.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider900.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider900.asColorSpec(),
        disabled = SushiRawColorTokens.Slate600.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green900.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green900.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow900.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow900.asColorSpec(),
        accentRed = SushiRawColorTokens.Red900.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red900.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange900.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange900.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple900.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple900.asColorSpec(),
        accentBrown = SushiRawColorTokens.Brown900.asColorSpec(),
        accentBrownIntense = SushiRawColorTokens.Brown900.asColorSpec(),
        accentPink = SushiRawColorTokens.Pink900.asColorSpec(),
        accentPinkIntense = SushiRawColorTokens.Pink900.asColorSpec(),
        brandOnlylight = SushiRawColorTokens.White.asColorSpec(),
        brand = themeColorScheme.v500,
        selection = themeColorScheme.v050,
        success = SushiRawColorTokens.Green500.asColorSpec(),
        warning = SushiRawColorTokens.Yellow800.asColorSpec(),
        error = SushiRawColorTokens.Orange800.asColorSpec(),
        offer = SushiRawColorTokens.Blue500.asColorSpec(),
        shimmer = SushiRawColorTokens.Slate700.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        backgroundDark = SushiRawColorTokens.White.asColorSpec(),
        default = SushiRawColorTokens.White.asColorSpec(),
        deepened = SushiRawColorTokens.White.asColorSpec(),
        errorDark = SushiRawColorTokens.White.asColorSpec(),
        brandOnlyLight = SushiRawColorTokens.White.asColorSpec(),
        successDark = SushiRawColorTokens.White.asColorSpec(),
        accentGrey = SushiRawColorTokens.White.asColorSpec(),
        accentTangerine = SushiRawColorTokens.White.asColorSpec(),
        discover = SushiRawColorTokens.White.asColorSpec(),
    ),
    borderColorScheme: SushiColorScheme.BorderColorScheme = SushiColorScheme.BorderColorScheme(
        subtle = SushiRawColorTokens.Slate800.asColorSpec(),
        moderate = SushiRawColorTokens.Slate700.asColorSpec(),
        intense = SushiRawColorTokens.Slate600.asColorSpec(),
        inverse = SushiRawColorTokens.Slate200.asColorSpec(),
        selection = themeColorScheme.v100,
        brand = themeColorScheme.v300,
        success = SushiRawColorTokens.Green300.asColorSpec(),
        warning = SushiRawColorTokens.Yellow300.asColorSpec(),
        error = SushiRawColorTokens.Orange300.asColorSpec(),
        accentRed = SushiRawColorTokens.Red800.asColorSpec(),
        accentRedIntense = SushiRawColorTokens.Red700.asColorSpec(),
        accentYellow = SushiRawColorTokens.Yellow800.asColorSpec(),
        accentYellowIntense = SushiRawColorTokens.Yellow700.asColorSpec(),
        accentCider = SushiRawColorTokens.Cider800.asColorSpec(),
        accentCiderIntense = SushiRawColorTokens.Cider700.asColorSpec(),
        accentPurple = SushiRawColorTokens.Purple800.asColorSpec(),
        accentPurpleIntense = SushiRawColorTokens.Purple700.asColorSpec(),
        accentGreen = SushiRawColorTokens.Green800.asColorSpec(),
        accentGreenIntense = SushiRawColorTokens.Green700.asColorSpec(),
        accentOrange = SushiRawColorTokens.Orange800.asColorSpec(),
        accentOrangeIntense = SushiRawColorTokens.Orange700.asColorSpec(),
        accentBlue = SushiRawColorTokens.Blue800.asColorSpec(),
        accentBlueIntense = SushiRawColorTokens.Blue700.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        dark = SushiRawColorTokens.White.asColorSpec(),
    ),
    crystalColorScheme: SushiColorScheme.CrystalColorScheme = SushiColorScheme.CrystalColorScheme(
        ontime = SushiRawColorTokens.Green800.asColorSpec(),
        delay = SushiRawColorTokens.Slate800.asColorSpec(),
        rain = SushiRawColorTokens.Indigo800.asColorSpec(),
        polylineAerialCurved = SushiRawColorTokens.Slate200.asColorSpec(),
    ),
    dishColorScheme: SushiColorScheme.DishColorScheme = SushiColorScheme.DishColorScheme(
        background = surfaceColorScheme.secondary,
        border = borderColorScheme.intense,
        icon = SushiRawColorTokens.Yellow200.asColorSpec(),
    ),
    resColorScheme: SushiColorScheme.ResColorScheme = SushiColorScheme.ResColorScheme(
        background50 = SushiRawColorTokens.Green800.asColorSpec(),
        background45 = SushiRawColorTokens.Green700.asColorSpec(),
        background40 = SushiRawColorTokens.Green600.asColorSpec(),
        background35 = SushiRawColorTokens.Green500.asColorSpec(),
        background30 = SushiRawColorTokens.Yellow500.asColorSpec(),
        background25 = SushiRawColorTokens.Orange400.asColorSpec(),
        background20 = SushiRawColorTokens.Orange400.asColorSpec(),
        background15 = SushiRawColorTokens.Orange400.asColorSpec(),
        background00 = SushiRawColorTokens.Slate500.asColorSpec(),
        backgroundNew = SushiRawColorTokens.Green800.asColorSpec(),
        borderNew = SushiRawColorTokens.Green600.asColorSpec(),
        label = SushiRawColorTokens.Slate100.asColorSpec(),
        labelNew = SushiRawColorTokens.Green200.asColorSpec(),
    ),
    buttonColorScheme: SushiColorScheme.ButtonColorScheme = SushiColorScheme.ButtonColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundPressed = themeColorScheme.v200,
        backgroundDisabled = SushiRawColorTokens.Slate500.asColorSpec(),   // revert to SushiSlate600.asColorSpec() ?
        primaryLabel = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelPressed = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryIcon = SushiRawColorTokens.White.asColorSpec(),
        primaryIconPressed = SushiRawColorTokens.White.asColorSpec(),
        primaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        secondaryBackground = SushiRawColorTokens.Transparent.asColorSpec(), // todox: revert to themeColorScheme.v500,
        secondaryBackgroundPressed = SushiRawColorTokens.Transparent.asColorSpec(), // todox: revert to themeColorScheme.v200,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelPressed = themeColorScheme.v500, // todox: revert to themeColorScheme.v200 ?,
        secondaryLabelDisabled = SushiRawColorTokens.Grey400.asColorSpec(), // todox: revert to SushiSlate400.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconPressed = themeColorScheme.v200,
        secondaryIconDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        ghostBackground = SushiRawColorTokens.Transparent.asColorSpec(), // todox: Revert to themeColorScheme.v500,
        ghostBackgroundPressed = SushiRawColorTokens.Transparent.asColorSpec(), // todox: revert to themeColorScheme.v200,
        ghostLabel = themeColorScheme.v500,
        ghostLabelPressed = themeColorScheme.v700,  // todox: revert to themeColorScheme.v200 ?
        ghostLabelDisabled = SushiRawColorTokens.Grey400.asColorSpec(), // todox: revert to SushiSlate600.asColorSpec(),
        ghostIcon = themeColorScheme.v500,
        ghostIconPressed = themeColorScheme.v200,
        ghostIconDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderPressed = themeColorScheme.v500, // todox: revert to themeColorScheme.v200 ?,
        secondaryBorderDisabled = SushiRawColorTokens.Grey400.asColorSpec(), // todox: revert to SushiSlate400.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        tertiaryBackground = SushiRawColorTokens.White.asColorSpec(),
        tertiaryBackgroundPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabel = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabelPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIcon = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIconPressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStroke = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStrokePressed = SushiRawColorTokens.White.asColorSpec(),
        tertiaryStrokeDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    stepperColorScheme: SushiColorScheme.StepperColorScheme = SushiColorScheme.StepperColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
        primaryIcon = SushiRawColorTokens.White.asColorSpec(),
        primaryIconDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryLabel = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelDisabled = SushiRawColorTokens.White.asColorSpec(),
        primaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBackground = themeColorScheme.v050,
        secondaryBackgroundDisabled = SushiRawColorTokens.Slate700.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconDisabled = SushiRawColorTokens.Slate500.asColorSpec(),
        secondaryLabelNumber = textColorScheme.primary,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelDisabled = SushiRawColorTokens.Slate500.asColorSpec(),
        secondaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBorder = themeColorScheme.v100,
        secondaryBorderDisabled = SushiRawColorTokens.Slate600.asColorSpec(),
    ),
    shimmerColorScheme: SushiColorScheme.ShimmerColorScheme = SushiColorScheme.ShimmerColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        start = SushiRawColorTokens.White.asColorSpec(),
        end = SushiRawColorTokens.White.asColorSpec(),
    ),
    sliderColorScheme: SushiColorScheme.SliderColorScheme = SushiColorScheme.SliderColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        background = SushiRawColorTokens.White.asColorSpec(),
        backgroundPressed = SushiRawColorTokens.White.asColorSpec(),
        backgroundDisabled = SushiRawColorTokens.White.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelPressed = SushiRawColorTokens.White.asColorSpec(),
        labelDisabled = SushiRawColorTokens.White.asColorSpec(),
        labelComplete = SushiRawColorTokens.White.asColorSpec(),
        icon = SushiRawColorTokens.White.asColorSpec(),
        iconPressed = SushiRawColorTokens.White.asColorSpec(),
        iconDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
    filterColorScheme: SushiColorScheme.FilterColorScheme = SushiColorScheme.FilterColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        backgroundSuccess = SushiRawColorTokens.White.asColorSpec(),
        stroke = SushiRawColorTokens.White.asColorSpec(),
        strokeSuccess = SushiRawColorTokens.White.asColorSpec(),
        strokeDisabled = SushiRawColorTokens.White.asColorSpec(),
        label = SushiRawColorTokens.White.asColorSpec(),
        labelDisabled = SushiRawColorTokens.White.asColorSpec(),
        icon = SushiRawColorTokens.White.asColorSpec(),
        iconDisabled = SushiRawColorTokens.White.asColorSpec(),
    ),
): SushiColorScheme =
    SushiColorScheme(
        schemeType = SushiColorSchemeType.Dark,
        material = materialColorScheme,
        grey = grey,
        red = red,
        green = green,
        blue = blue,
        yellow = yellow,
        purple = purple,
        indigo = indigo,
        brown = brown,
        cider = cider,
        teal = teal,
        orange = orange,
        pink = pink,
        lime = lime,
        corn = corn,
        avacado = avacado,
        gold = gold,
        onion = onion,
        charcoal = charcoal,
        honey = honey,
        tangerine = tangerine,
        slate = slate,
        rating = rating,
        theme = themeColorScheme,
        text = textColorScheme,
        icon = iconColorScheme,
        surface = surfaceColorScheme,
        border = borderColorScheme,
        crystal = crystalColorScheme,
        dish = dishColorScheme,
        res = resColorScheme,
        button = buttonColorScheme,
        stepper = stepperColorScheme,
        shimmer = shimmerColorScheme,
        slider = sliderColorScheme,
        filter = filterColorScheme
    )