@file:OptIn(ExperimentalSushiApi::class)

package com.zomato.sushi.compose.foundation

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import com.zomato.sushi.compose.atoms.color.asColorSpec

fun sushiDarkColorScheme(
    materialColorScheme: ColorScheme = darkColorScheme(),
    themeColorScheme: SushiColorScheme.ThemeColorScheme = SushiColorScheme.ThemeColorScheme(
        v050 = SushiRed050.asColorSpec(),
        v100 = SushiRed100.asColorSpec(),
        v200 = SushiRed200.asColorSpec(),
        v300 = SushiRed300.asColorSpec(),
        v400 = SushiRed400.asColorSpec(),
        v500 = SushiRed500.asColorSpec(),
        v600 = SushiRed600.asColorSpec(),
        v700 = SushiRed700.asColorSpec(),
        v800 = SushiRed800.asColorSpec(),
        v900 = SushiRed900.asColorSpec(),
        accentColor = SushiRed600.asColorSpec(),
    ),
    textColorScheme: SushiColorScheme.TextColorScheme = SushiColorScheme.TextColorScheme(
        default = SushiSlate050.asColorSpec(),
        primary = SushiSlate100.asColorSpec(),
        secondary = SushiSlate300.asColorSpec(),
        tertiary = SushiSlate400.asColorSpec(),
        quaternary = SushiSlate500.asColorSpec(),
        disabled = SushiSlate600.asColorSpec(),
        inverse = SushiSlate900.asColorSpec(),
        brand = themeColorScheme.v500,
        brandOnlyLight = SushiSlate100.asColorSpec(),  // textPrimary
        offer = SushiBlue300.asColorSpec(),
        success = SushiGreen300.asColorSpec(),
        warning = SushiYellow300.asColorSpec(),
        error = SushiOrange300.asColorSpec(),
        accentRed = SushiRed200.asColorSpec(),
        accentRedIntense = SushiRed100.asColorSpec(),
        accentOrange = SushiOrange200.asColorSpec(),
        accentOrangeIntense = SushiOrange100.asColorSpec(),
        accentGreen = SushiGreen200.asColorSpec(),
        accentGreenIntense = SushiGreen100.asColorSpec(),
        accentBlue = SushiBlue200.asColorSpec(),
        accentBlueIntense = SushiBlue100.asColorSpec(),
        accentPurple = SushiPurple200.asColorSpec(),
        accentPurpleIntense = SushiPurple100.asColorSpec(),
        accentYellow = SushiYellow100.asColorSpec(),
        accentYellowIntense = SushiYellow050.asColorSpec(),
        accentTeal = SushiTeal200.asColorSpec(),
        accentTealIntense = SushiTeal100.asColorSpec(),
        accentCider = SushiCider200.asColorSpec(),
        accentCiderIntense = SushiCider100.asColorSpec(),
        accentBrown = SushiBrown200.asColorSpec(),
        accentBrownIntense = SushiBrown100.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        light = SushiWhite.asColorSpec(),
        accentPink = SushiWhite.asColorSpec(),
        discover = SushiWhite.asColorSpec(),
    ),
    iconColorScheme: SushiColorScheme.IconColorScheme = SushiColorScheme.IconColorScheme(
        default = SushiSlate050.asColorSpec(),
        primary = SushiSlate100.asColorSpec(),
        secondary = SushiSlate300.asColorSpec(),
        tertiary = SushiSlate400.asColorSpec(),
        quaternary = SushiSlate500.asColorSpec(),
        offer = SushiBlue300.asColorSpec(),
        warning = SushiYellow300.asColorSpec(),
        error = SushiOrange300.asColorSpec(),
        success = SushiGreen700.asColorSpec(),
        inverse = SushiSlate900.asColorSpec(),
        brand = themeColorScheme.v500,
        disabled = SushiSlate100.asColorSpec(),
        brandOnlyLight = SushiSlate600.asColorSpec(),
        accentOrange = SushiOrange400.asColorSpec(),
        accentRed = SushiRed400.asColorSpec(),
        accentGreen = SushiGreen400.asColorSpec(),
        accentBlue = SushiBlue400.asColorSpec(),
        accentPurple = SushiPurple400.asColorSpec(),
        accentYellow = SushiYellow300.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        light = SushiWhite.asColorSpec(),
        enable = SushiWhite.asColorSpec(),
        accentPink = SushiWhite.asColorSpec(),
        accentTeal = SushiWhite.asColorSpec(),
        discover = SushiWhite.asColorSpec(),
    ),
    surfaceColorScheme: SushiColorScheme.SurfaceColorScheme = SushiColorScheme.SurfaceColorScheme(
        backgroundPrimary = SushiSlate900.asColorSpec(),
        backgroundSecondary = SushiSlate900.asColorSpec(),
        primary = SushiSlate800.asColorSpec(),
        secondary = SushiSlate700.asColorSpec(),
        elevated = SushiSlate700.asColorSpec(),
        inverse = SushiSlate050.asColorSpec(),
        inset = SushiSlate800.asColorSpec(),
        insetIntense = SushiSlate700.asColorSpec(),
        accentBlue = SushiYellow900.asColorSpec(),
        accentBlueIntense = SushiYellow900.asColorSpec(),
        accentCider = SushiBlue900.asColorSpec(),
        accentCiderIntense = SushiBlue900.asColorSpec(),
        disabled = SushiRed900.asColorSpec(),
        accentGreen = SushiRed900.asColorSpec(),
        accentGreenIntense = SushiOrange900.asColorSpec(),
        accentYellow = SushiOrange900.asColorSpec(),
        accentYellowIntense = SushiPurple900.asColorSpec(),
        accentRed = SushiPurple900.asColorSpec(),
        accentRedIntense = SushiCider900.asColorSpec(),
        accentOrange = SushiCider900.asColorSpec(),
        accentOrangeIntense = SushiGreen900.asColorSpec(),
        accentPurple = SushiGreen900.asColorSpec(),
        accentPurpleIntense = SushiBrown900.asColorSpec(),
        accentBrown = SushiBrown900.asColorSpec(),
        accentBrownIntense = SushiPink900.asColorSpec(),
        accentPink = SushiPink900.asColorSpec(),
        accentPinkIntense = themeColorScheme.v050,
        brandOnlylight = SushiGreen500.asColorSpec(),
        brand = SushiYellow800.asColorSpec(),
        selection = SushiOrange800.asColorSpec(),
        success = SushiSlate600.asColorSpec(),
        warning = SushiWhite.asColorSpec(),
        error = themeColorScheme.v500,
        offer = SushiBlue500.asColorSpec(),
        shimmer = SushiSlate700.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        backgroundDark = SushiWhite.asColorSpec(),
        default = SushiWhite.asColorSpec(),
        deepened = SushiWhite.asColorSpec(),
        errorDark = SushiWhite.asColorSpec(),
        brandOnlyLight = SushiWhite.asColorSpec(),
        successDark = SushiWhite.asColorSpec(),
        accentGrey = SushiWhite.asColorSpec(),
        accentTangerine = SushiWhite.asColorSpec(),
        discover = SushiWhite.asColorSpec(),
    ),
    borderColorScheme: SushiColorScheme.BorderColorScheme = SushiColorScheme.BorderColorScheme(
        subtle = SushiSlate800.asColorSpec(),
        moderate = SushiSlate700.asColorSpec(),
        intense = SushiSlate600.asColorSpec(),
        inverse = SushiSlate200.asColorSpec(),
        selection = themeColorScheme.v100,
        brand = themeColorScheme.v300,
        success = SushiGreen300.asColorSpec(),
        warning = SushiYellow300.asColorSpec(),
        error = SushiOrange300.asColorSpec(),
        accentRed = SushiRed800.asColorSpec(),
        accentRedIntense = SushiRed700.asColorSpec(),
        accentYellow = SushiYellow800.asColorSpec(),
        accentYellowIntense = SushiYellow700.asColorSpec(),
        accentCider = SushiCider800.asColorSpec(),
        accentCiderIntense = SushiCider700.asColorSpec(),
        accentPurple = SushiPurple800.asColorSpec(),
        accentPurpleIntense = SushiPurple700.asColorSpec(),
        accentGreen = SushiGreen800.asColorSpec(),
        accentGreenIntense = SushiGreen700.asColorSpec(),
        accentOrange = SushiOrange800.asColorSpec(),
        accentOrangeIntense = SushiOrange700.asColorSpec(),
        accentBlue = SushiBlue800.asColorSpec(),
        accentBlueIntense = SushiBlue700.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        dark = SushiWhite.asColorSpec(),
    ),
    crystalColorScheme: SushiColorScheme.CrystalColorScheme = SushiColorScheme.CrystalColorScheme(
        ontime = SushiGreen800.asColorSpec(),
        delay = SushiSlate800.asColorSpec(),
        rain = SushiIndigo800.asColorSpec(),
        polylineAerialCurved = SushiSlate200.asColorSpec(),
    ),
    dishColorScheme: SushiColorScheme.DishColorScheme = SushiColorScheme.DishColorScheme(
        background = surfaceColorScheme.secondary,
        border = borderColorScheme.intense,
        icon = SushiYellow200.asColorSpec(),
    ),
    resColorScheme: SushiColorScheme.ResColorScheme = SushiColorScheme.ResColorScheme(
        background50 = SushiGreen800.asColorSpec(),
        background45 = SushiGreen700.asColorSpec(),
        background40 = SushiGreen600.asColorSpec(),
        background35 = SushiGreen500.asColorSpec(),
        background30 = SushiYellow500.asColorSpec(),
        background25 = SushiOrange400.asColorSpec(),
        background20 = SushiOrange400.asColorSpec(),
        background15 = SushiOrange400.asColorSpec(),
        background00 = SushiSlate500.asColorSpec(),
        backgroundNew = SushiGreen800.asColorSpec(),
        borderNew = SushiGreen600.asColorSpec(),
        label = SushiSlate100.asColorSpec(),
        labelNew = SushiGreen200.asColorSpec(),
    ),
    buttonColorScheme: SushiColorScheme.ButtonColorScheme = SushiColorScheme.ButtonColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundPressed = themeColorScheme.v200,
        backgroundDisabled = SushiSlate600.asColorSpec(),
        primaryLabel = SushiWhite.asColorSpec(),
        primaryLabelPressed = SushiWhite.asColorSpec(),
        primaryLabelDisabled = SushiWhite.asColorSpec(),
        primaryIcon = SushiWhite.asColorSpec(),
        primaryIconPressed = SushiWhite.asColorSpec(),
        primaryIconDisabled = SushiWhite.asColorSpec(),
        secondaryBackground = themeColorScheme.v500,
        secondaryBackgroundPressed = themeColorScheme.v200,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelPressed = themeColorScheme.v200,
        secondaryLabelDisabled = SushiSlate600.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconPressed = themeColorScheme.v200,
        secondaryIconDisabled = SushiSlate600.asColorSpec(),
        ghostBackground = themeColorScheme.v500,
        ghostBackgroundPressed = themeColorScheme.v200,
        ghostLabel = themeColorScheme.v500,
        ghostLabelPressed = themeColorScheme.v200,
        ghostLabelDisabled = SushiSlate600.asColorSpec(),
        ghostIcon = themeColorScheme.v500,
        ghostIconPressed = themeColorScheme.v200,
        ghostIconDisabled = SushiSlate600.asColorSpec(),
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderPressed = themeColorScheme.v200,
        secondaryBorderDisabled = SushiSlate600.asColorSpec(),
        // todox: Fix with actual values, after defaults are merged in View sushi.
        tertiaryBackground = SushiWhite.asColorSpec(),
        tertiaryBackgroundPressed = SushiWhite.asColorSpec(),
        tertiaryLabel = SushiWhite.asColorSpec(),
        tertiaryLabelPressed = SushiWhite.asColorSpec(),
        tertiaryLabelDisabled = SushiWhite.asColorSpec(),
        tertiaryIcon = SushiWhite.asColorSpec(),
        tertiaryIconPressed = SushiWhite.asColorSpec(),
        tertiaryIconDisabled = SushiWhite.asColorSpec(),
        tertiaryStroke = SushiWhite.asColorSpec(),
        tertiaryStrokePressed = SushiWhite.asColorSpec(),
        tertiaryStrokeDisabled = SushiWhite.asColorSpec(),
    ),
    stepperColorScheme: SushiColorScheme.StepperColorScheme = SushiColorScheme.StepperColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundDisabled = SushiSlate600.asColorSpec(),
        primaryIcon = SushiWhite.asColorSpec(),
        primaryIconDisabled = SushiWhite.asColorSpec(),
        primaryLabel = SushiWhite.asColorSpec(),
        primaryLabelDisabled = SushiWhite.asColorSpec(),
        primaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBackground = themeColorScheme.v050,
        secondaryBackgroundDisabled = SushiSlate700.asColorSpec(),
        secondaryIcon = themeColorScheme.v500,
        secondaryIconDisabled = SushiSlate500.asColorSpec(),
        secondaryLabelNumber = textColorScheme.primary,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelDisabled = SushiSlate500.asColorSpec(),
        secondaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBorder = themeColorScheme.v100,
        secondaryBorderDisabled = SushiSlate600.asColorSpec(),
    ),
    shimmerColorScheme: SushiColorScheme.ShimmerColorScheme = SushiColorScheme.ShimmerColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        start = SushiWhite.asColorSpec(),
        end = SushiWhite.asColorSpec(),
    ),
    sliderColorScheme: SushiColorScheme.SliderColorScheme = SushiColorScheme.SliderColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        background = SushiWhite.asColorSpec(),
        backgroundPressed = SushiWhite.asColorSpec(),
        backgroundDisabled = SushiWhite.asColorSpec(),
        label = SushiWhite.asColorSpec(),
        labelPressed = SushiWhite.asColorSpec(),
        labelDisabled = SushiWhite.asColorSpec(),
        labelComplete = SushiWhite.asColorSpec(),
        icon = SushiWhite.asColorSpec(),
        iconPressed = SushiWhite.asColorSpec(),
        iconDisabled = SushiWhite.asColorSpec(),
    ),
    filterColorScheme: SushiColorScheme.FilterColorScheme = SushiColorScheme.FilterColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        backgroundSuccess = SushiWhite.asColorSpec(),
        stroke = SushiWhite.asColorSpec(),
        strokeSuccess = SushiWhite.asColorSpec(),
        strokeDisabled = SushiWhite.asColorSpec(),
        label = SushiWhite.asColorSpec(),
        labelDisabled = SushiWhite.asColorSpec(),
        icon = SushiWhite.asColorSpec(),
        iconDisabled = SushiWhite.asColorSpec(),
    ),
): SushiColorScheme =
    SushiColorScheme(
        schemeType = SushiColorSchemeType.Dark,
        material = materialColorScheme,
        theme = themeColorScheme,
        text = textColorScheme,
        icon = iconColorScheme,
        surface = surfaceColorScheme,
        border = borderColorScheme,
        crystal = crystalColorScheme,
        dish = dishColorScheme,
        res = resColorScheme,
        button = buttonColorScheme,
        stepper = stepperColorScheme,
        shimmer = shimmerColorScheme,
        slider = sliderColorScheme,
        filter = filterColorScheme
    )