@file:OptIn(ExperimentalSushiApi::class)

package com.zomato.sushi.compose.foundation

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.lightColorScheme

fun sushiLightColorScheme(
    materialColorScheme: ColorScheme = lightColorScheme(),
    themeColorScheme: SushiColorScheme.ThemeColorScheme = SushiColorScheme.ThemeColorScheme(
        v050 = SushiRed050,
        v100 = SushiRed100,
        v200 = SushiRed200,
        v300 = SushiRed300,
        v400 = SushiRed400,
        v500 = SushiRed500,
        v600 = SushiRed600,
        v700 = SushiRed700,
        v800 = SushiRed800,
        v900 = SushiRed900,
        accentColor = SushiRed500,
    ),
    textColorScheme: SushiColorScheme.TextColorScheme = SushiColorScheme.TextColorScheme(
        default = SushiBlack,
        primary = SushiGrey900,
        secondary = SushiGrey700,
        tertiary = SushiGrey600,
        quaternary = SushiGrey500,
        disabled = SushiGrey400,
        inverse = SushiWhite,
        brand = themeColorScheme.v500,
        brandOnlyLight = themeColorScheme.v500,  // textBrand
        offer = SushiBlue500,
        success = SushiGreen500,
        warning = SushiYellow500,
        error = SushiOrange600,
        accentRed = SushiRed500,
        accentRedIntense = SushiRed700,
        accentOrange = SushiOrange500,
        accentOrangeIntense = SushiOrange800,
        accentGreen = SushiGreen500,
        accentGreenIntense = SushiGreen800,
        accentBlue = SushiBlue500,
        accentBlueIntense = SushiBlue800,
        accentPurple = SushiPurple500,
        accentPurpleIntense = SushiPurple800,
        accentYellow = SushiYellow600,
        accentYellowIntense = SushiYellow800,
        accentTeal = SushiTeal500,
        accentTealIntense = SushiTeal700,
        accentCider = SushiCider500,
        accentCiderIntense = SushiCider700,
        accentBrown = SushiBrown500,
        accentBrownIntense = SushiBrown700,
        // todox: Fix with actual values, after defaults are merged in View sushi.
        light = SushiWhite,
        accentPink = SushiWhite,
        discover = SushiWhite,
    ),
    iconColorScheme: SushiColorScheme.IconColorScheme = SushiColorScheme.IconColorScheme(
        default = SushiBlack,
        primary = SushiGrey900,
        secondary = SushiGrey700,
        tertiary = SushiGrey600,
        quaternary = SushiGrey500,
        offer = SushiBlue500,
        warning = SushiYellow500,
        error = SushiOrange600,
        success = SushiGreen500,
        inverse = SushiWhite,
        brand = themeColorScheme.v500,
        disabled = SushiGrey400,
        brandOnlyLight = themeColorScheme.v500,
        accentOrange = SushiOrange500,
        accentRed = SushiRed500,
        accentGreen = SushiGreen500,
        accentBlue = SushiBlue500,
        accentPurple = SushiPurple500,
        accentYellow = SushiYellow400,
        // todox: Fix with actual values, after defaults are merged in View sushi.
        light = SushiWhite,
        enable = SushiWhite,
        accentPink = SushiWhite,
        accentTeal = SushiWhite,
        discover = SushiWhite,
    ),
    surfaceColorScheme: SushiColorScheme.SurfaceColorScheme = SushiColorScheme.SurfaceColorScheme(
        backgroundPrimary = SushiWhite,
        backgroundSecondary = SushiIndigo050,
        primary = SushiWhite,
        secondary = SushiWhite,
        elevated = SushiGrey100,
        inverse = SushiBlack,
        inset = SushiGrey050,
        insetIntense = SushiGrey100,
        accentBlue = SushiBlue050,
        accentBlueIntense = SushiBlue100,
        accentCider = SushiCider050,
        accentCiderIntense = SushiCider100,
        disabled = SushiGrey500,
        accentGreen = SushiGreen050,
        accentGreenIntense = SushiGreen100,
        accentYellow = SushiYellow050,
        accentYellowIntense = SushiYellow100,
        accentRed = SushiRed050,
        accentRedIntense = SushiRed100,
        accentOrange = SushiOrange050,
        accentOrangeIntense = SushiOrange100,
        accentPurple = SushiPurple050,
        accentPurpleIntense = SushiPurple100,
        accentBrown = SushiBrown050,
        accentBrownIntense = SushiBrown100,
        accentPink = SushiPink050,
        accentPinkIntense = SushiPink100,
        brandOnlylight = themeColorScheme.v500,
        brand = themeColorScheme.v500,
        selection = themeColorScheme.v050,
        success = SushiGreen500,
        warning = SushiYellow500,
        error = SushiOrange600,
        offer = SushiBlue500,
        shimmer = SushiGrey100,
        shimmerInset = SushiGrey050,
        // todox: Fix with actual values, after defaults are merged in View sushi.
        backgroundDark = SushiWhite,
        default = SushiWhite,
        deepened = SushiWhite,
        errorDark = SushiWhite,
        brandOnlyLight = SushiWhite,
        successDark = SushiWhite,
        accentGrey = SushiWhite,
        accentTangerine = SushiWhite,
        discover = SushiWhite,
    ),
    borderColorScheme: SushiColorScheme.BorderColorScheme = SushiColorScheme.BorderColorScheme(
        subtle = SushiGrey100,
        moderate = SushiGrey200,
        intense = SushiGrey200,
        inverse = SushiSlate600,
        selection = themeColorScheme.v500,
        brand = themeColorScheme.v500,
        success = SushiGreen500,
        warning = SushiYellow500,
        error = SushiOrange600,
        accentRed = SushiRed100,
        accentRedIntense = SushiRed200,
        accentYellow = SushiYellow100,
        accentYellowIntense = SushiYellow200,
        accentCider = SushiCider100,
        accentCiderIntense = SushiCider200,
        accentPurple = SushiPurple100,
        accentPurpleIntense = SushiPurple200,
        accentGreen = SushiGreen100,
        accentGreenIntense = SushiGreen200,
        accentOrange = SushiOrange100,
        accentOrangeIntense = SushiOrange200,
        accentBlue = SushiBlue100,
        accentBlueIntense = SushiBlue200,
        // todox: Fix with actual values, after defaults are merged in View sushi.
        dark = SushiWhite,
    ),
    crystalColorScheme: SushiColorScheme.CrystalColorScheme = SushiColorScheme.CrystalColorScheme(
        ontime = SushiGreen600,
        delay = SushiWhite,
        rain = SushiIndigo500,
        polylineAerialCurved = SushiBlack,
    ),
    dishColorScheme: SushiColorScheme.DishColorScheme = SushiColorScheme.DishColorScheme(
        background = SushiYellow050,
        border = SushiYellow200,
        icon = SushiYellow400,
    ),
    resColorScheme: SushiColorScheme.ResColorScheme = SushiColorScheme.ResColorScheme(
        background50 = SushiGreen800,
        background45 = SushiGreen700,
        background40 = SushiGreen600,
        background35 = SushiGreen500,
        background30 = SushiYellow400,
        background25 = SushiOrange400,
        background20 = SushiOrange400,
        background15 = SushiOrange400,
        background00 = SushiGrey500,
        backgroundNew = SushiGreen100,
        borderNew = SushiGreen300,
        label = SushiWhite,
        labelNew = SushiGreen600,
    ),
    buttonColorScheme: SushiColorScheme.ButtonColorScheme = SushiColorScheme.ButtonColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundPressed = themeColorScheme.v600,
        backgroundDisabled = SushiGrey400,
        primaryLabel = SushiWhite,
        primaryLabelPressed = SushiWhite,
        primaryLabelDisabled = SushiWhite,
        primaryIcon = SushiWhite,
        primaryIconPressed = SushiWhite,
        primaryIconDisabled = SushiWhite,
        secondaryBackground = SushiWhite,    // todox: revert to themeColorScheme.v500 ?,
        secondaryBackgroundPressed = themeColorScheme.v600,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelPressed = SushiWhite,
        secondaryLabelDisabled = SushiGrey050,
        secondaryIcon = themeColorScheme.v500,
        secondaryIconPressed = themeColorScheme.v600,
        secondaryIconDisabled = iconColorScheme.disabled,
        ghostBackground = SushiTransparent,    // todox: revert to themeColorScheme.v500 ?,
        ghostBackgroundPressed = themeColorScheme.v600,
        ghostLabel = themeColorScheme.v600, //  todox: revert to SushiGrey400 ?,
        ghostLabelPressed = themeColorScheme.accentColor,
        ghostLabelDisabled = SushiGrey400,   // todox: revert to themeColorScheme.v600 ?,
        ghostIcon = themeColorScheme.v500,
        ghostIconPressed = themeColorScheme.v600,
        ghostIconDisabled = textColorScheme.disabled,
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderPressed = themeColorScheme.v500,
        secondaryBorderDisabled = iconColorScheme.disabled,
        // todox: Fix with actual values, after defaults are merged in View sushi.
        tertiaryBackground = SushiWhite,
        tertiaryBackgroundPressed = SushiWhite,
        tertiaryLabel = SushiWhite,
        tertiaryLabelPressed = SushiWhite,
        tertiaryLabelDisabled = SushiWhite,
        tertiaryIcon = SushiWhite,
        tertiaryIconPressed = SushiWhite,
        tertiaryIconDisabled = SushiWhite,
        tertiaryStroke = SushiWhite,
        tertiaryStrokePressed = SushiWhite,
        tertiaryStrokeDisabled = SushiWhite,
    ),
    stepperColorScheme: SushiColorScheme.StepperColorScheme = SushiColorScheme.StepperColorScheme(
        primaryBackground = themeColorScheme.v500,
        primaryBackgroundDisabled = SushiGrey400,
        primaryIcon = SushiWhite,
        primaryIconDisabled = SushiWhite,
        primaryLabel = SushiWhite,
        primaryLabelDisabled = SushiWhite,
        primaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBackground = themeColorScheme.v050,
        secondaryBackgroundDisabled = SushiGrey100,
        secondaryIcon = themeColorScheme.v500,
        secondaryIconDisabled = SushiGrey400,
        secondaryLabelNumber = textColorScheme.primary,
        secondaryLabel = themeColorScheme.v500,
        secondaryLabelDisabled = SushiGrey400,
        secondaryLabelCustomisable = textColorScheme.quaternary,
        secondaryBorder = themeColorScheme.v500,
        secondaryBorderDisabled = SushiGrey400,
    ),
    shimmerColorScheme: SushiColorScheme.ShimmerColorScheme = SushiColorScheme.ShimmerColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        start = SushiWhite,
        end = SushiWhite,
    ),
    sliderColorScheme: SushiColorScheme.SliderColorScheme = SushiColorScheme.SliderColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        background = SushiWhite,
        backgroundPressed = SushiWhite,
        backgroundDisabled = SushiWhite,
        label = SushiWhite,
        labelPressed = SushiWhite,
        labelDisabled = SushiWhite,
        labelComplete = SushiWhite,
        icon = SushiWhite,
        iconPressed = SushiWhite,
        iconDisabled = SushiWhite,
    ),
    filterColorScheme: SushiColorScheme.FilterColorScheme = SushiColorScheme.FilterColorScheme(
        // todox: Fix with actual values, after defaults are merged in View sushi.
        backgroundSuccess = SushiWhite,
        stroke = SushiWhite,
        strokeSuccess = SushiWhite,
        strokeDisabled = SushiWhite,
        label = SushiWhite,
        labelDisabled = SushiWhite,
        icon = SushiWhite,
        iconDisabled = SushiWhite,
    ),
): SushiColorScheme =
    SushiColorScheme(
        schemeType = SushiColorSchemeType.Light,
        material = materialColorScheme,
        theme = themeColorScheme,
        text = textColorScheme,
        icon = iconColorScheme,
        surface = surfaceColorScheme,
        border = borderColorScheme,
        crystal = crystalColorScheme,
        dish = dishColorScheme,
        res = resColorScheme,
        button = buttonColorScheme,
        stepper = stepperColorScheme,
        shimmer = shimmerColorScheme,
        slider = sliderColorScheme,
        filter = filterColorScheme
    )