package com.zomato.sushi.compose.foundation

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.unit.em
import androidx.compose.ui.unit.sp

internal object SushiTypographyTokens {
    val Light050: TextStyle = TextStyle(fontSize = SushiTextSize050, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light100: TextStyle = TextStyle(fontSize = SushiTextSize100, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light200: TextStyle = TextStyle(fontSize = SushiTextSize200, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light300: TextStyle = TextStyle(fontSize = SushiTextSize300, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light400: TextStyle = TextStyle(fontSize = SushiTextSize400, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light500: TextStyle = TextStyle(fontSize = SushiTextSize500, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light600: TextStyle = TextStyle(fontSize = SushiTextSize600, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light700: TextStyle = TextStyle(fontSize = SushiTextSize700, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light800: TextStyle = TextStyle(fontSize = SushiTextSize800, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Light900: TextStyle = TextStyle(fontSize = SushiTextSize900, fontWeight = SushiFontWeight.Light.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular050: TextStyle = TextStyle(fontSize = SushiTextSize050, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular100: TextStyle = TextStyle(fontSize = SushiTextSize100, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular200: TextStyle = TextStyle(fontSize = SushiTextSize200, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular300: TextStyle = TextStyle(fontSize = SushiTextSize300, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular400: TextStyle = TextStyle(fontSize = SushiTextSize400, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular500: TextStyle = TextStyle(fontSize = SushiTextSize500, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular600: TextStyle = TextStyle(fontSize = SushiTextSize600, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular700: TextStyle = TextStyle(fontSize = SushiTextSize700, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular800: TextStyle = TextStyle(fontSize = SushiTextSize800, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Regular900: TextStyle = TextStyle(fontSize = SushiTextSize900, fontWeight = SushiFontWeight.Regular.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium050: TextStyle = TextStyle(fontSize = SushiTextSize050, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium100: TextStyle = TextStyle(fontSize = SushiTextSize100, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium200: TextStyle = TextStyle(fontSize = SushiTextSize200, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium300: TextStyle = TextStyle(fontSize = SushiTextSize300, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium400: TextStyle = TextStyle(fontSize = SushiTextSize400, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium500: TextStyle = TextStyle(fontSize = SushiTextSize500, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium600: TextStyle = TextStyle(fontSize = SushiTextSize600, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium700: TextStyle = TextStyle(fontSize = SushiTextSize700, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium800: TextStyle = TextStyle(fontSize = SushiTextSize800, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Medium900: TextStyle = TextStyle(fontSize = SushiTextSize900, fontWeight = SushiFontWeight.Medium.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold050: TextStyle = TextStyle(fontSize = SushiTextSize050, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold100: TextStyle = TextStyle(fontSize = SushiTextSize100, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold200: TextStyle = TextStyle(fontSize = SushiTextSize200, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold300: TextStyle = TextStyle(fontSize = SushiTextSize300, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold400: TextStyle = TextStyle(fontSize = SushiTextSize400, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold500: TextStyle = TextStyle(fontSize = SushiTextSize500, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold600: TextStyle = TextStyle(fontSize = SushiTextSize600, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold700: TextStyle = TextStyle(fontSize = SushiTextSize700, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold800: TextStyle = TextStyle(fontSize = SushiTextSize800, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val SemiBold900: TextStyle = TextStyle(fontSize = SushiTextSize900, fontWeight = SushiFontWeight.SemiBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold050: TextStyle = TextStyle(fontSize = SushiTextSize050, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold100: TextStyle = TextStyle(fontSize = SushiTextSize100, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold200: TextStyle = TextStyle(fontSize = SushiTextSize200, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold300: TextStyle = TextStyle(fontSize = SushiTextSize300, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold400: TextStyle = TextStyle(fontSize = SushiTextSize400, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold500: TextStyle = TextStyle(fontSize = SushiTextSize500, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold600: TextStyle = TextStyle(fontSize = SushiTextSize600, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold700: TextStyle = TextStyle(fontSize = SushiTextSize700, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold800: TextStyle = TextStyle(fontSize = SushiTextSize800, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val Bold900: TextStyle = TextStyle(fontSize = SushiTextSize900, fontWeight = SushiFontWeight.Bold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold050: TextStyle = TextStyle(fontSize = SushiTextSize050, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold100: TextStyle = TextStyle(fontSize = SushiTextSize100, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold200: TextStyle = TextStyle(fontSize = SushiTextSize200, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold300: TextStyle = TextStyle(fontSize = SushiTextSize300, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold400: TextStyle = TextStyle(fontSize = SushiTextSize400, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold500: TextStyle = TextStyle(fontSize = SushiTextSize500, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold600: TextStyle = TextStyle(fontSize = SushiTextSize600, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold700: TextStyle = TextStyle(fontSize = SushiTextSize700, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold800: TextStyle = TextStyle(fontSize = SushiTextSize800, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
    val ExtraBold900: TextStyle = TextStyle(fontSize = SushiTextSize900, fontWeight = SushiFontWeight.ExtraBold.fontWeight(), fontFamily = OkraFontFamily, lineHeight = 1.2.em, letterSpacing = 0.0.sp)
}